/**
 * Club-name catalogue derived from openfootball/clubs (CC0-1.0).
 * This is simulation input only; it is not a live provider feed.
 */
export const SIMULATION_CLUBS = [
  '07 Vestur',
  '1. CfR Pforzheim',
  '1. FC Düren',
  '1. FC Heidenheim',
  '1. FC Kaan-Marienborn',
  '1. FC Kaiserslautern',
  '1. FC Köln',
  '1. FC Lok Stendal',
  '1. FC Lokomotive Leipzig (1966-1991)',
  '1. FC Magdeburg',
  '1. FC Neubrandenburg 04',
  '1. FC Nürnberg',
  '1. FC Phönix Lübeck',
  '1. FC Rielasingen-Arlen',
  '1. FC Saarbrücken',
  '1. FC Schweinfurt 05',
  '1. FC Slovácko',
  '1. FC Tatran Prešov',
  '1. FC Union Berlin',
  '1. FK Příbram',
  '1. FSV Mainz 05',
  '1. SC Sollenau',
  '1. SC Znojmo FK',
  '1. SK Prostějov',
  '1. Wiener Neustädter SC',
  '1899 Hoffenheim',
  '2 de Mayo',
  '3 de Febrero',
  'A.C. ChievoVerona',
  'A.C. Milan',
  'A.F.C. Bournemouth',
  'A.S. Roma',
  'Aalborg BK',
  'Aalborg Boldspilklub',
  'Aalesunds FK',
  'Aarhus Gymnastikforening',
  'AB Argir',
  'ABC FC RN',
  'Aberdare Athletic FC (1893-1928)',
  'Aberdeen F.C.',
  'Aberdeen FC',
  'Aberystwyth Town FC',
  'Abha',
  'AC Ajaccio',
  'AC Ancona',
  'AC Arles-Avignon',
  'AC Bellinzona',
  'AC Cesena',
  'AC Cesena (1940-2018)',
  'AC Chievo Verona',
  'AC Horsens',
  'AC Juvenes-Dogana',
  'AC Libertas',
  'AC Malcantone',
  'AC Marinhense',
  'AC Milan',
  'AC Mineros',
  'AC Monza',
  'AC Nagano Parceiro',
  'AC Omonia Nicosia',
  'AC Oulu',
  'AC Perugia',
  'AC Pisa',
  'AC Reggiana',
  'AC Renate',
  'AC Sparta Prague',
  'AC Sparta Praha',
  'AC Taverne',
  'AC Vantaan Allianssi (2002-2006)',
  'Academia Cantolao',
  'Academia Puerto Cabello',
  'Academica SC',
  'Académica de Coimbra',
  'Académico Viseu',
  'Accrington FC (1878-1896)',
  'Accrington Stanley F.C.',
  'Accrington Stanley FC',
  'ACD Treviso',
  'ACF Fiorentina',
  'ACR Messina SSD',
  'AD Alcorcón',
  'AD Comerciantes FC',
  'AD Guanacasteca',
  'AD Municipal Liberia',
  'AD San Carlos',
  'AD São Caetano',
  'Adana Demirspor',
  'Adanaspor',
  'Adelaide United',
  'Adenauerring 17 // 76131 Karlsruhe',
  'Admira Landhaus',
  'ADO Den Haag',
  'ADR Jicaral',
  'ADT Tarma',
  'AE Kifisia FC',
  'AE Larissa FC',
  'AEK Athens FC',
  'AEK Larnaca FC',
  'AEL Kalloni FC',
  'AEL Limassol',
  'AEZ Zakakiou',
  'AF Elbasani',
  'Afan Lido FC',
  'AFC Ajax',
  'AFC Ann Arbor',
  'AFC Bournemouth',
  'AFC Eskilstuna',
  'AFC Fylde',
  'AFC Rushden & Diamonds',
  'AFC Telford United',
  'AFC Tubize',
  'AFC Turris-Oltul',
  'AFC Wimbledon',
  'AGF Aarhus',
  'Agropecuario Argentino',
  'AIK',
  'Airdrieonians',
  'AJ Auxerre',
  'Ajax Amsterdam',
  'Akademisk Boldklub',
  'Akhisar Belediyespor',
  'Akhisarspor',
  'Akhmat Grozny',
  'Akropolis IF',
  'Akçaabat Sebatspor',
  'Al Ahed',
  'Al Ahli Doha SC',
  'Al Ahly',
  'Al Ain FC',
  'Al Batin FC',
  'Al Gharafa SC',
  'Al Ittihad Al Sakandary',
  'Al Khoor',
  'Al Masry SC',
  'Al Mokawloon Al Arab',
  'Al Qadsiah FC',
  'Al Shahaniya',
  'Al Wehdat',
  'Al-Ahli',
  'Al-Duhail SC',
  'Al-Ettifaq',
  'Al-Fateh',
  'Al-Fayha',
  'Al-Hazem',
  'Al-Hilal',
  'Al-Ittihad',
  'Al-Jandal',
  'Al-Khaleej',
  'Al-Nassr',
  'Al-Okhdood',
  'Al-Raed',
  'Al-Riyadh',
  'Al-Sadd SC',
  'Al-Shabab',
  'Al-Taawoun',
  'Al-Tai',
  'Al-Wehda',
  'Alanyaspor',
  'Alashkert FC',
  'Albacete Balompié',
  'Albion Rovers',
  'Albirex Niigata',
  'Albirex Niigata FC',
  'Aldershot Town FC',
  'Aldosivi',
  'Alebrijes de Oaxaca',
  'Alemannia Aachen',
  'Alessandria',
  'Alfreton Town FC',
  'Algeciras CF',
  'ALHCS Spartan FC',
  'Alianza Atlético',
  'Alianza FC',
  'Alianza Lima',
  'Alianza Petrolera FC (1990-2024)',
  'Alianza Universidad',
  'Alianza Valledupar',
  'Alicante CF',
  'Alki Larnaca FC (1948-2014)',
  'Alki Oroklini',
  'All Boys',
  'Alloa Athletic',
  'Almagro',
  'Almere City FC',
  'Alpha United FC',
  'Altamira',
  'Altay SK',
  'Altrincham FC',
  'Altınordu',
  'Alvarado',
  'Am Eliaspark 1 // 03042 Cottbus',
  'Am Sportpark 1 // 85053 Ingolstadt',
  'Amarante FC',
  'Amazonas FC',
  'AmaZulu Durban',
  'America RJ',
  'Amica Wrońki (1992-2007)',
  'Amiens SC',
  'Amsterdamsche FC',
  'América de Cali',
  'América de Natal',
  'América de Quito',
  'América Futebol Clube (MG)',
  'América MG',
  'An der Wuhlheide 263 // 12555 Berlin',
  'Anadia FC',
  'Angers SCO',
  'Angoulême-Soyaux Charente',
  'Ankara Keçiörengücü',
  'Annagh United FC',
  'Annan Athletic',
  'Anorthosis Famagusta FC',
  'Antalyaspor',
  'Antigua GFC',
  'Antwerpen',
  'Antwerpen › Vlaanderen | Antwerpen',
  'AO Trikala',
  'APO Akratitos',
  'APOEL Nicosia FC',
  'Apollon Limassol FC',
  'Apollon Pontou FC',
  'Apollon Smyrnis FC',
  'APOP/Kinyras Peyias FC',
  'Aqvital FC Csákvár',
  'Aragua FC',
  'Araks Ararat (-2005)',
  'Ararat-Armenia FC',
  'Araz FK Naxçıvan',
  'Arbroath',
  'Ards FC',
  'Arena Straße 1 // 40474 Düsseldorf',
  'Argentinos Juniors',
  'Ariana FC',
  'Aris Limassol FC',
  'Aris Thessaloniki FC',
  'Arka Gdynia',
  'Arminia Bielefeld',
  'Arnett Gardens',
  'Arsenal de Sarandí',
  'Arsenal F.C.',
  'Arsenal FC',
  'Arsenal Tula',
  'AS Beauvais Oise',
  'AS Béziers',
  'AS Cannes',
  'AS FAR',
  'AS FC Buzău',
  'AS Gubbio',
  'AS Haute-Broye',
  'AS Livorno',
  'AS Livorno Calcio',
  'AS Lucchese Libertas',
  'AS Monaco',
  'AS Monaco FC',
  'AS Nancy Lorraine',
  'AS Progresul București',
  'AS Roma',
  'AS Saint-Priest',
  'AS Saint-Étienne',
  'AS San Giovanni',
  'AS Trenčín',
  'AS Vita Club',
  'ASA Târgu Mureș (2008-2018)',
  'ASC Götzendorf',
  'Ascoli',
  'ASD Castel di Sangro',
  'ASD Nocerina',
  'ASD Savoia',
  'ASD US Grosseto',
  'ASD Virtus Bergamo',
  'Ashington AFC',
  'ASI Audax Friul',
  'ASK Bad Vöslau',
  'ASK Baumgarten',
  'ASK Bravo Publikum',
  'ASK Ebreichsdorf',
  'ASK Elektra Wien (-2021)',
  'ASK Klagenfurt',
  'ASK Kottingbrunn',
  'ASK St. Valentin',
  'ASK Voitsberg',
  'ASK Vorwärts Berlin # champs (6): 1969/70 1967..1965 (2) 1963..1961 (2) 1959/60',
  'ASK-BSC Bruck/Leitha',
  'ASKÖ Donau Linz',
  'ASKÖ Gmünd',
  'ASKÖ Köttmannsdorf',
  'ASKÖ Oedt',
  'ASKÖ Pasching (1946-2007)',
  'ASKÖ Stinatz',
  'ASOA Valence',
  'Associação Atlética Ponte Preta',
  'Associação Chapecoense de Futebol',
  'Asteras Tripolis FC',
  'Aston Villa',
  'Aston Villa F.C.',
  'Aston Villa FC',
  'Astra Giurgiu',
  'ASV Annabichler SV',
  'ASV Draßburg',
  'ASV Schrems',
  'ASV Siegendorf',
  'ASV Spratzern',
  'Aswan SC',
  'Atalanta B.C.',
  'Atalanta Bergamo',
  'Atherton Collieries',
  'Athinaikos AS FC',
  'Athletic Bilbao',
  'Athletic Club Bilbao',
  'Athlone Town AFC',
  'Atlanta',
  'Atlanta United FC',
  'Atlante',
  'Atlante FC',
  'Atlas',
  "Atlètic Club d'Escaldes",
  'Atlético Bucaramanga',
  'Atlético Clube Goianiense',
  'Atlético El Vigía',
  'Atlético FC',
  'Atlético GO',
  'Atlético Huila',
  'Atlético Madrid',
  'Atlético MG',
  'Atlético Morelia',
  'Atlético Nacional',
  'Atlético PR',
  'Atlético Rafaela',
  'Atlético San Luis',
  'Atlético Tucumán',
  'Atlético Venezuela',
  'Atromitos FC',
  'ATSV Ober-Grafendorf',
  'ATSV Stadl-Paura',
  'ATSV Wolfsberg',
  'ATUS Ferlach',
  'ATUS Velden',
  'Auckland City FC',
  'Audax Italiano',
  'AUK Broughton FC',
  'Austin Bold FC',
  'Austin FC',
  'Austria Klagenfurt',
  'Austria Kärnten (2007-2010)',
  'Austria Lustenau',
  'Austria Salzburg',
  'Av Revolución 846-B',
  'Av. Camelinas No.',
  'Av. Jacarandas s/n esq. Av. España Fraccionamiento Virginia Boca del Río // Veracruz',
  'Av. Mayapán esq. Av. Kabah s/n Supermanzana 43 Pedregal del Bosque // Quintana Roo',
  'Av. Patria',
  'Avaí FC',
  'Avellino',
  'Avispa Fukuoka',
  'AVS Futebol',
  'Ayacucho FC',
  'Ayr United',
  'AZ Alkmaar',
  'B 1901 Nykøbing (1901-1994)',
  'B 1903 København (1903-1992)',
  'B 1908 Amager',
  'B 1909 Odense',
  'B 1913 Odense',
  'B36 Tórshavn',
  'B68 Toftir # champs (1): 1993/94',
  'B71 Sandoy',
  'B93 København',
  'Baden-Württemberg',
  'Bahlinger SC',
  'Bakı FK',
  'Bala Town FC',
  'Baladiyat El Mahalla',
  'Balestier Khalsa',
  'Ballinamallard United FC',
  'Ballymena United FC',
  'Balzan FC',
  'Balıkesirspor',
  'Bandırmaspor',
  'Bangor City FC',
  'Bangor FC',
  'Baniyas Club',
  'BANKRUPT Ardwick FC',
  'BANKRUPT Newton Heath FC',
  'Barcelona Guayaquil',
  'Bari',
  'Barnet FC',
  'Barnsley F.C.',
  'Barnsley FC',
  'Baroka',
  'Barracas Central',
  'Barranquilla FC',
  'Barrow AFC',
  'Barry Town AFC',
  'Bath City FC',
  'Bayer 04 Leverkusen',
  'Bayer Leverkusen',
  'Bayern',
  'Bayern München',
  'Bačka Topola',
  'Bedfordshire',
  'Beerschot VAC (1899-1999)',
  'Beijing Renhe',
  'Beijing Renhe F.C.',
  'Beijing Sinobo Guoan',
  'Beitar Jerusalem F.C.',
  'Beitar Jerusalem FC',
  'Beitar Tel Aviv Bat Yam FC',
  'Belenenses SAD',
  'Benevento Calcio',
  'Bergantiños FC',
  'Bergen [nl]',
  'Berkshire',
  'Berlin',
  'Berliner AK 07',
  'Berwick Rangers',
  'Besa St. Gallen',
  'Betim FC',
  'Beşiktaş İstanbul',
  'Beşiktaş J.K.',
  'BFC Daugavpils',
  'BFC Dynamo Berlin',
  'BFC Preussen',
  'BFC Siófok',
  'Bidwest Wits',
  'Billericay Town FC',
  'Birkirkara FC',
  'Birmingham & West Midlands | West Midlands ## note: added Birmingham - why? why not?',
  'Birmingham City F.C.',
  'Birmingham City FC',
  'Birmingham Legion FC',
  'Bischofshofen Sportklub',
  'Bismarckstr. 122 - 124 // 51373 Leverkusen',
  'BK Frem',
  'BK Fremad Amager',
  'BK Häcken',
  'BK Olympic',
  'Black Leopards',
  'Black Rock FC',
  'Blackburn Rovers F.C.',
  'Blackburn Rovers FC',
  'Blackpool F.C.',
  'Blackpool FC',
  'Blau-Weiß 90 Berlin (-1992)',
  'Blaublitz Akita',
  'Bloemfontein Celtic',
  'Bnei Sakhnin F.C.',
  'Bnei Sakhnin FC',
  'Bnei Yehuda Tel Aviv F.C.',
  'Bnei Yehuda Tel-Aviv FC',
  'Boavista F.C.',
  'Boavista FC',
  'Boca Juniors',
  'Boca Juniors de Cali',
  'Boca Juniors Gibraltar FC',
  'Bodrum',
  'Bodø/Glimt',
  'Bogotá FC',
  'Bohemian FC',
  'Bohemians',
  'Bohemians Praha',
  'Bologna F.C.',
  'Bologna FC',
  'Bolton Wanderers F.C.',
  'Bolton Wanderers FC',
  'Boluspor',
  'Bonner SC',
  'Bonnyrigg Rose',
  'Bootle FC (1879-1893)',
  'Bor. Mönchengladbach',
  'Boreham Wood FC',
  'Borussia Dortmund',
  "Borussia M'gladbach",
  'Borussia Mönchengladbach',
  'Boston River',
  'Boston United FC',
  'Botafogo de Futebol e Regatas',
  'Botafogo Futebol Clube (SP)',
  'Botafogo RJ',
  'Botafogo SP',
  'Boulevard Adolfo López Mateos',
  'Bourg-en-Bresse 01',
  'Boyacá Chicó',
  'Bradford City A.F.C.',
  'Bradford City AFC',
  'Bradford Park Avenue AFC',
  'Braintree Town FC',
  'Brandenburg',
  'Brasil RS',
  'Brasiliense FC',
  'Brasília FC',
  'Bray Wanderers FC',
  'Brazos Valley Cavalry FC',
  'Brechin City',
  'Breiðablik',
  'Bremen',
  'Bremer SV',
  'Brentford F.C.',
  'Brentford FC',
  'Brera Strumica',
  'Brescia Calcio',
  'Brighton & Hove Albion F.C.',
  'Brighton & Hove Albion FC',
  'Brisbane Roar',
  'Bristol & Gloucestershire | Gloucestershire',
  'Bristol City F.C.',
  'Bristol City FC',
  'Bristol Rovers F.C.',
  'Bristol Rovers FC',
  'Briton Ferry Llansawel AFC',
  'Bromley FC',
  'Brown',
  'Bruk-Bet Termalica Nieciecza',
  'Brusque FC',
  'Brussels',
  'Bryne FK',
  'Brøndby IF',
  'Brønshøj BK',
  'BSC Hastedt',
  'BSC Young Boys',
  'BSG Chemie Leipzig',
  'BSV Schwarz-Weiß Rehden',
  'BSV SW Rehden',
  'Bucaspor',
  'Buckinghamshire',
  'Budafoki MTE',
  'Budapest Honvéd FC',
  'Budapesti VSC',
  'Budaörsi SC',
  'Buenos Aires',
  'Burgenland',
  'Burgos CF',
  'Buriram United FC',
  'Burnley F.C.',
  'Burnley FC',
  'Bursaspor',
  'Burton Albion F.C.',
  'Burton Albion FC',
  'Burton Swifts FC (1871-1901)',
  'Burton United FC (1901-1910)',
  'Burton Wanderers FC',
  'Burton Wanderers FC (1871-1901)',
  'Bury F.C.',
  'Bury FC',
  "Busan I'Park",
  'BV De Graafschap',
  'BW Lohne',
  'Békéscsaba 1912 Előre',
  'Büyükşehir Belediye Erzurumspor',
  'C.D. Aves',
  'C.D. Feirense',
  'C.D. Guadalajara',
  'C.D. Nacional',
  'C.D. Santa Clara',
  'C.D. Tondela',
  'C.F. Monterrey',
  'C.F. Pachuca',
  'C.S. Marítimo',
  'CA Antoniano',
  'CA Bastia',
  'CA Bragantino (1928-2019)',
  'CA Cerro',
  'CA Independiente de Avellaneda',
  'CA Independiente de La Chorrera',
  'CA Lanús',
  'CA Los Andes',
  'CA Osasuna',
  'CA Peñarol',
  'CA Progreso',
  'CA Rentistas',
  'CA River Plate',
  'CA Tigre',
  'Cabinteely FC',
  'Caernarfon Town FC',
  'Caersws FC',
  'Cafetaleros de Chiapas',
  'Cagliari Calcio',
  'Cal FC',
  'Calcio Catania',
  'Calcio Foggia',
  'Calcio Lecco',
  'Calcio Padova',
  'Caledonia AIA # Malabar is a residential district incorporated into the borough of Arima',
  'Calle del Toro No. 100',
  'Calle Totonacas No. 560',
  'Calz. Ignacio Zaragoza No. 666',
  'Calz. Territorio Santos Modelo No. 1',
  'Calzada de las Etnias s/n',
  'Cambridge United F.C.',
  'Cambridge United FC',
  'Cambridgeshire',
  'Cancún FC',
  'Cangzhou Mighty',
  'Canterbury United',
  'Canvey Island FC',
  'Cape Town City',
  'Cape Town Spurs',
  'Carabobo FC',
  'Caracas FC',
  'Cardiff City F.C.',
  'Cardiff City FC',
  'Cardiff Metropolitan University FC',
  'Carlisle United F.C.',
  'Carlisle United FC',
  'Carlos A. Mannucci',
  'Carmarthen Town AFC',
  'Carmelita',
  'Carpi',
  'Carrarese Calcio',
  'Carrick Rangers FC',
  'Carshalton Athletic FC',
  'Casa Pia',
  'Castroper Straße 145 // 44791 Bochum',
  'Cavalier',
  'Cavalry FC',
  'CAY Berrechid',
  'CD Alcoyano',
  'CD Antofagasta',
  'CD Atlético Baleares',
  'CD Aves',
  'CD Badajoz',
  'CD Becerril',
  'CD Calahorra',
  'CD Castellón',
  'CD Chivas USA (2005-2014)',
  'CD Cobresal',
  'CD Cova Piedade',
  'CD Cuenca',
  'CD Ebro',
  'CD El Álamo',
  'CD Eldense',
  'CD Feirense',
  'CD Guadalajara',
  'CD Guadalajara Chivas',
  'CD Guastatoya',
  'CD Huachipato',
  'CD Jorge Wilstermann',
  'CD Leganés',
  'CD Logroñés',
  'CD Lugo',
  'CD Mafra',
  'CD Magallanes',
  'CD Malacateco',
  'CD Maldonado',
  'CD Marathón',
  'CD Mirandés',
  'CD Nacional Madeira',
  'CD Numancia',
  'CD Olimpia',
  'CD Olmedo',
  'CD Ourense',
  'CD Palestino',
  'CD Peña Azagresa',
  'CD Santa Clara',
  'CD Tapatío',
  'CD Tenerife',
  'CD Toledo',
  'CD Tondela',
  'CD Trofense',
  'CD Técnico Universitario',
  'CD Universidad Católica del Ecuador',
  'CD Universidad de Concepción',
  'CD Victoria',
  'CD Ñublense',
  'CE Carroi',
  'CE Principat (1989-2015)',
  'CE Sabadell',
  'Ceahlăul Piatra Neamț',
  'Ceará Sporting Club',
  'Cefn Druids AFC',
  'Celaya',
  'Celtic F.C.',
  'Celtic FC',
  'Central Coast Mariners',
  'Central Córdoba',
  'Central Córdoba de Santiago del Estero',
  'Centro Atlético Fénix',
  'Centro Sportivo Alagoano',
  'Ceramica Cleopatra',
  'Cercle Brugge',
  'Cercle Brugge K.S.V.',
  'Cercle Brugge KSV',
  'Cerezo Osaka',
  'Cerro Largo',
  'Cerro Porteño',
  'Ceára SC',
  'CF Badalona',
  'CF Ciudad de Murcia',
  "CF Esperança d'Andorra",
  'CF Estrela da Amadora',
  'CF Extremadura (-2010)',
  'CF Fuenlabrada',
  'CF Illueca',
  'CF Lorca Deportiva',
  'CF Monterrey',
  'CF Montréal',
  'CF Pachuca',
  'CF Rayo Majadahonda',
  'CF Reus',
  'CF Spartanii Sportul Selemet',
  'CF Villanovense',
  'CFR Cluj',
  'Chacarita Juniors',
  'Chaco For Ever',
  'Chalkidona FC',
  'Chamois Niortais FC',
  'Changchun Yatai',
  'Chapecoense',
  'Charleston Battery',
  'Charlotte FC',
  'Charlotte Independence',
  'Charlton Athletic F.C.',
  'Charlton Athletic FC',
  'Chattanooga Red Wolves',
  'Chelsea F.C.',
  'Chelsea FC',
  'Cheltenham Town F.C.',
  'Cheltenham Town FC',
  'Chemnitzer FC',
  'Chengdu Rongcheng',
  'Chernomorets Novorosisk',
  'Cheshire',
  'Chester FC',
  'Chesterfield FC',
  'Chiapas Fútbol Club',
  'Chicago Fire',
  'Chicago Fire Soccer Club',
  'Chichester City FC',
  'Chimia Râmnicu Vâlcea (1946-2004)',
  'Chindia Târgoviște',
  'Chippa United',
  'Chippenham Town FC',
  'Chivas USA',
  'Chongqing Dangdai Lifan',
  'Chongqing Dangdai Lifan F.C.',
  'Chorley FC',
  'Chorrillo FC',
  'Chrobry Głogów',
  'Chunnam Dragons',
  'Chur 97',
  'Cimarrones de Sonora',
  'Cittadella',
  'Clermont Foot 63',
  'Cliftonville FC',
  'Club Always Ready',
  'Club América',
  'Club Athletico Paranaense',
  'Club Atlas',
  'Club Atlas de Guadalajara',
  'Club Atlético Aldosivi',
  'Club Atlético Banfield',
  'Club Atlético Belgrano',
  'Club Atlético Colón',
  'Club Atlético Grau',
  'Club Atlético Independiente',
  'Club Atlético La Paz',
  'Club Atlético Lanús',
  'Club Atlético Patronato',
  'Club Atlético River Plate',
  'Club Atlético Vélez Sarsfield',
  'Club Aurora',
  'Club Blooming',
  'Club Bolívar',
  'Club Brugge',
  'Club Brugge KV',
  'Club Cienciano',
  'Club de Fútbol Atlante',
  'Club de Fútbol Monterrey',
  'Club de Fútbol Pachuca',
  'Club de Fútbol Tigres de la Universidad Autónoma de Nuevo León',
  'Club de Gimnasia y Esgrima La Plata',
  'Club Deportivo FAS',
  'Club Deportivo Guabirá',
  'Club Deportivo Guadalajara',
  'Club Deportivo Oriente Petrolero',
  'Club Deportivo San José',
  'Club Deportivo Universidad de San Martín de Porres',
  'Club Deportivo Águila',
  'Club Deportivo Árabe Unido',
  'Club Destroyers',
  'Club General Díaz',
  'Club Guaraní',
  'Club León',
  'Club Marino Luanco',
  'Club Nacional',
  'Club Necaxa',
  'Club Olimpia',
  'Club Plaza Colonia de Deportes',
  'Club Puebla',
  'Club River Plate',
  'Club Santos Laguna',
  'Club Sol de América',
  'Club Sport Rosario',
  'Club Sportivo San Lorenzo',
  'Club Tijuana',
  'Club Toluca',
  'Club Universidad Nacional',
  'Club Universitario de Deportes',
  'Club Xelajú MC',
  'Clube Atlético Mineiro',
  'Clube de Regatas Brasil',
  'Clube de Regatas do Flamengo',
  'Clube do Remo',
  'Clyde',
  'Clydebank F.C.',
  'Clydebank FC',
  'Cobh Ramblers FC',
  'Cobán Imperial',
  'Colchester United F.C.',
  'Colchester United FC',
  'Coleraine FC',
  'College 1975 FC',
  'College Europa FC',
  'Colo-Colo',
  'Colorado Rapids',
  'Colorado Springs Switchbacks FC',
  'Columbus Crew',
  'Columbus Crew SC',
  'Colón Santa Fe',
  'Comerciantes Unidos',
  'Comillas CF',
  'Como',
  'Compesieres FC',
  'Comunicaciones FC',
  'Concordia Basel',
  'Concordia Chiajna',
  "Connah's Quay Nomads FC",
  'Consadole Sapporo',
  'Constellació Esportiva (1998-2000)',
  'Coquimbo Unido',
  'Corinthians SP',
  'Coritiba Foot Ball Club',
  'Coritiba PR',
  'Cork Celtic FC (1951-1979)',
  'Cork City FC',
  'Cork Hibernians FC (1957-1976)',
  'Cornwall',
  'Corona Brașov (2010-2014)',
  'Correcaminos',
  'Cosenza Calcio',
  'Cove Rangers FC',
  'Coventry City F.C.',
  'Coventry City FC',
  'Cowdenbeath',
  'CP Mérida',
  'CR Vasco da Gama',
  'Crawley Town F.C.',
  'Crawley Town FC',
  'CRB AL',
  'Crewe Alexandra F.C.',
  'Crewe Alexandra FC',
  'Criciúma EC',
  'Criciúma Esporte Clube',
  'Crucero del Norte',
  'Crusaders FC',
  'Cruz Azul',
  'Cruz Azul Hidalgo',
  'Cruzeiro Esporte Clube',
  'Cruzeiro MG',
  'Crystal Palace',
  'Crystal Palace F.C.',
  'Crystal Palace FC',
  'CS Alagoano',
  'CS Cartaginés',
  'CS Chenois',
  'CS Corvinul Hunedoara',
  'CS Emelec',
  'CS Fola Esch',
  'CS Grevenmacher',
  'CS Herediano',
  'CS Louhans-Cuiseaux',
  'CS Marítimo',
  'CS Minaur Baia Mare',
  'CS Mioveni',
  'CS Miramar Misiones',
  'CS Petrocub Hîncești',
  'CS Pétange (1910-2015)',
  'CS Sedan-Ardennes',
  'CS Tiligul-Tiras Tiraspol (1938-2009)',
  'CS Tunari',
  'CS Turnu Severin',
  'CSC 1599 Șelimbăr',
  'CSD Macará',
  'CSD Municipal',
  'Csepel SC',
  'CSF Bălți',
  'CSKA Moskva',
  'CSM Flacăra Moreni',
  'CSM Jiul Petroșani',
  'CSU Voința Sibiu (2007-2012)',
  'CU Fabril Barreiro',
  'Cuiabá',
  'Cuiabá Esporte Clube',
  'Cultural Leonesa',
  'Cumbayá',
  'Cumbria',
  'Curicó Unido',
  'Cusco FC',
  'Cwmbrân Town AFC',
  'Cádiz CF',
  'Córdoba CF',
  'Córdoba | Provincia Córdoba',
  'Cúcuta Deportivo',
  'D.C. United',
  'Daco-Getica București',
  'Daegu FC',
  'Daejeon Citizen',
  'Dagenham & Redbridge FC',
  'Dalian Pro (2009-2024)',
  'Dalian Yifang F.C.',
  'Dalkurd FF',
  'Dalvík/Reynir',
  'Damac',
  'Danubio FC',
  'Dardania St. Gallen',
  'Darlington FC',
  'Dartford FC',
  'Darwen FC (1870-2009)',
  'Dayton Dutch Lions',
  'De Graafschap',
  'Debreceni VSC',
  'Defensa y Justicia',
  'Defensor Sporting',
  'Defensores de Belgranes',
  'Degerfors IF',
  'Delfines',
  'Delfín SC',
  'Denizlispor',
  'Deportes Iquique',
  'Deportes La Serena',
  'Deportes Melipilla',
  'Deportes Quindío',
  'Deportes Tolima',
  'Deportes Vallenar',
  'Deportivo Alavés',
  'Deportivo Anzoátegui',
  'Deportivo Binacional FC',
  'Deportivo Cali',
  'Deportivo Capiatá',
  'Deportivo Coopsol',
  'Deportivo Español',
  'Deportivo Garcilaso',
  'Deportivo Iztapa',
  'Deportivo La Guaira',
  'Deportivo Lara',
  'Deportivo Llacuabamba',
  'Deportivo Mandiyú',
  'Deportivo Mixco',
  'Deportivo Morón',
  'Deportivo Municipal',
  'Deportivo Pasto',
  'Deportivo Pereira',
  'Deportivo Petare',
  'Deportivo Quito',
  'Deportivo Riestra',
  'Deportivo Sanarate',
  'Deportivo Santaní',
  'Deportivo Saprissa',
  'Deportivo Siquinalá',
  'Deportivo Toluca',
  'Deportivo Toluca FC',
  'Deportivo Táchira',
  'Derby County F.C.',
  'Derby County FC',
  'Derbyshire',
  'Derry City FC',
  'Des Moines Menace',
  'Desna Chernihiv',
  'Desportiva Ferroviária',
  'Desportivo de Chaves',
  'Deutschlandsberger SC',
  'Devon',
  'DFK Dainava',
  'Diamond FC',
  'Digenis Morphou',
  'Dijon FCO',
  'Dinamo București',
  'Dinamo St. Petersburg',
  'Diyarbakırspor',
  'Diósgyőri VTK',
  'DJK Vilzing',
  'Djurgårdens IF',
  'Docks United FC',
  'Don Bosco Weg 1 // 9400 Wolfsberg',
  'Donauwörther Str. 170 // 86154 Augsburg',
  'Doncaster Rovers F.C.',
  'Doncaster Rovers FC',
  'Dorados Sinaloa',
  'Dorking Wanderers FC',
  'Dornbirner SV',
  'Dorset',
  'DOS Utrecht',
  'Dover Athletic FC',
  'Doxa Dramas FC',
  'Doxa Katokopia FC',
  'Drogheda United FC',
  'Droylsden FC',
  'Drumcondra FC',
  'DSV Leoben',
  'Dublin City FC (1999-2006)',
  'Dukla Banská Bystrica',
  'Duluth FC',
  'Dulwich Hamlet FC',
  'Dumbarton',
  'Dunaújváros FC (1952-2009)',
  'Dunbeholden',
  'Dundalk FC',
  'Dundee F.C.',
  'Dundee FC',
  'Dundee United',
  'Dundee United F.C.',
  'Dundela FC',
  'Dunfermline Athletic',
  'Dungannon Swifts FC',
  'Dunărea Călărași',
  'Durham',
  'Durham City AFC',
  'DWS Amsterdam',
  'Dynamo Dresden',
  'Dynamo Moscow',
  'Dynamo Moskva',
  'Dyskobolia Grodzisk Wielkopolski',
  'EA Guingamp',
  'East Fife',
  'East Kilbride FC',
  'East Stirlingshire F.C.',
  'East Stirlingshire FC',
  'East Sussex | Sussex',
  'East Yorkshire | Yorkshire',
  'Eastbourne Borough FC',
  'Eastern Suburbs',
  'Eastleigh FC',
  'EB/Streymur',
  'Ebbsfleet United FC',
  'EC Bahia',
  'EC Vitória',
  'Edessaikos FC',
  'Edinburgh City',
  'Egaleo FC',
  'Egersunds IK',
  'Ehime FC',
  'Eintracht Braunschweig',
  'Eintracht Frankfurt',
  'Eintracht Norderstedt',
  'Eintracht Trier',
  'Ekenäs IF',
  'El Dakhleya',
  'El Entag El Harby',
  'El Farolito',
  'El Gouna',
  'El Nacional',
  'El Palmar CF',
  'El Paso Locomotive FC',
  'El Tanque Sisley',
  'Elazığspor',
  'Elche CF',
  'Elgin City',
  'Empoli F.C.',
  'Empoli FC',
  'En Avant de Guingamp',
  'Energie Cottbus',
  'Enforcers FC',
  'Enosis Neon Paralimni FC',
  'Enppi',
  'ENPPI SC',
  'Entre Ríos | Provincia Entre Ríos',
  'Envigado FC',
  'EPA Larnaca (1930-1994)',
  'Ergotelis FC',
  'Erie Commodores FC',
  'Ermis Aradippou FC',
  'Ernst-Kuzorra-Weg 1 // 45891 Gelsenkirchen',
  'Erzgebirge Aue',
  'Erzincanspor',
  'Erzurumspor',
  'ES Troyes AC',
  'Esbjerg fB',
  'Eskilsminne IF',
  'Eskişehirspor',
  'Esporte Clube Bahia',
  'Esporte Clube Juventude',
  'Esporte Clube São Bento',
  'Esporte Clube Vitória',
  'Espérance Sportive de Tunis',
  'Essex',
  'ESTAC Troyes',
  'Estadio Universitario',
  'Estoril Praia',
  'Estudiantes de Buenos Aires',
  'Estudiantes de Caracas',
  'Estudiantes de La Plata',
  'Estudiantes de Mérida',
  'Estudiantes de Río Cuarto',
  'Estudiantes LP',
  'Estudiantes UAG',
  'Ethnikos Achnas FC',
  'Ethnikos Asteras FC',
  'Ethnikos Piraeus FC',
  'Etoile Carouge FC',
  'Europa Point FC',
  'Everton de Viña del Mar',
  'Everton F.C.',
  'Everton FC',
  'Evian Thonon Gaillard F.C.',
  'Excelsior Maassluis',
  'Excelsior Virton',
  'Exeter City F.C.',
  'Exeter City FC',
  'Extremadura UD',
  'Eyüpspor',
  'F.C. Ashdod',
  'F.C. Copenhagen',
  'F.C. Hansa Rostock',
  'F91 Dudelange',
  'FA Šiauliai',
  'Fagiano Okayama',
  'Falkenbergs FF',
  'Falkirk',
  'Farsley Celtic FC',
  'Fatih Karagümrük',
  'Favoritner AC',
  'FBC Melgar',
  'FBK Karlstad',
  'FBK Kaunas',
  'FC 08 Homburg',
  'FC 08 Villingen',
  'FC Aarau',
  'FC Academica Clinceni',
  'FC Admira Wacker',
  'FC Admira Wacker Mödling',
  'FC Aemme',
  'FC Affoltern',
  'FC Ajka',
  'FC Ajoie-Monterri',
  'FC Akhmat Grozny',
  'FC Akron Tolyatti',
  'FC Aktobe',
  'FC Alania Vladikavkaz',
  'FC Alberschwende',
  'FC Allschwil',
  'FC Alma-Ata (2000-2008)',
  'FC Altstätten',
  'FC Alverca',
  'FC Ameri Tbilisi (2002-2009)',
  'FC Amkar Perm',
  'FC Amsterdam (1972-1982)',
  'FC Andorra',
  'FC Annecy',
  'FC Anzhi Makhachkala',
  'FC Ararat Yerevan',
  'FC Arda Kardzhali',
  'FC Argeș Pitești',
  'FC Aris Bonnevoie (-2001)',
  'FC Armavir',
  'FC Arouca',
  'FC Arsenal Dzerzhinsk',
  'FC Arsenal Kyiv',
  'FC Arsenal Tula',
  'FC Ashdod',
  'FC Astana',
  'FC Astana-1964 # champs (2): 2007/08 2002/03',
  'FC Atyrau',
  'FC Augsburg',
  'FC Avangard Kursk',
  'FC Avenir Beggen',
  'FC Baden',
  'FC Ballkani',
  'FC Baltika',
  'FC Baltimore',
  'FC Baník Ostrava',
  'FC Barcelona',
  'FC Barreirense',
  'FC Basel',
  'FC BATE Borisov',
  'FC Bavois',
  'FC Bayern Munich',
  'FC Begnins',
  'FC Belshina Bobruisk',
  'FC Bergheim',
  'FC Besa Biel/Bienne',
  'FC Biel-Bienne',
  'FC Bischofszell',
  'FC BKMA Yerevan',
  'FC Black Stars Basel',
  'FC Blau-Weiß Linz',
  'FC Blue Boys Muhlenbach',
  'FC Bosporus',
  'FC Botoșani',
  'FC Brașov',
  'FC Breitenrain',
  'FC Breitenrain Bern',
  'FC Bubendorf',
  'FC Buchs AG',
  'FC Bulle',
  'FC Carl Zeiss Jena',
  'FC Carlos Stein',
  'FC Cartagena',
  'FC Chambly',
  'FC Champel',
  'FC Chatel St. Denis',
  'FC Chayka',
  'FC Chernomorets Novorossiysk',
  'FC Chertanovo Moskva',
  'FC Chiasso',
  'FC Chikhura Sachkhere',
  'FC Chornomorets Odesa',
  'FC Cincinnati',
  'FC Codru',
  'FC Coffrane',
  "FC Collina d'Oro",
  'FC Courtételle',
  'FC Crotone',
  'FC CSL',
  'FC DAC 1904 Dunajská Streda',
  'FC Dacia Buiucani',
  'FC Dacia Chișinău',
  'FC Dallas',
  'FC Dardania Lausanne',
  'FC Daugava Daugavpils',
  'FC Daugava Rīga (2003-2015)',
  'FC Den Bosch',
  'FC Denver',
  'FC Deutschkreutz',
  'FC Dietikon',
  'FC Differdange 03',
  'FC Dila Gori',
  'FC Dinaburg',
  'FC Dinamo Batumi',
  'FC Dinamo Brest',
  'FC Dinamo City',
  'FC Dinamo Minsk',
  'FC Dinamo Tbilisi',
  'FC Dinamo-93 Minsk (1992-1998)',
  'FC Dinamo-Auto Tiraspol',
  'FC Dnepr Mogilev',
  'FC Dnipro',
  'FC Dnyapro Mogilev',
  'FC Domagnano',
  'FC Dordrecht',
  'FC Dornbirn',
  'FC Dorogi',
  'FC Dunav Ruse',
  'FC Dynamo Kyiv',
  'FC Dynamo Moscow',
  'FC Dübendorf',
  'FC Dürrenast',
  'FC Džiugas',
  'FC Echallens',
  'FC Echichens',
  'FC Edmonton',
  'FC Eindhoven',
  'FC Einheit Wernigerode',
  'FC Eintracht Bamberg',
  'FC Emmen',
  'FC Encamp',
  'FC Energie Cottbus',
  'FC Erzgebirge Aue',
  'FC Escholzmatt-Marbach',
  'FC Etar Veliko Tarnovo',
  'FC Etzella Ettelbruck',
  'FC Extensiv Craiova (1949-2013)',
  'FC Fakel Voronezh',
  'FC Famalicão',
  'FC Fastav Zlín',
  'FC Felgueiras',
  'FC Fiorentino',
  'FC Flora Tallinn',
  'FC Floresti',
  'FC Fredericia',
  'FC Frutigen',
  'FC Gagra',
  'FC Gambarogno',
  'FC Gambarogno-Contone | FC Gambarogno',
  'FC Gandzasar',
  'FC Gandzasar Kapan',
  'FC Genolier-Begnins',
  'FC Gifu',
  'FC Girondins de Bordeaux',
  'FC Gland',
  'FC Gleisdorf 09',
  'FC Goldstern',
  'FC Gomel',
  'FC Gorodeya',
  'FC Grand-Saconnex',
  'FC Gratkorn',
  'FC Greifensee',
  'FC Groningen',
  'FC Gueugnon',
  'FC Gunzwil',
  'FC Gütersloh',
  'FC Haka',
  'FC Haka Valkeakoski',
  'FC Halifax Town',
  'FC Hard',
  'FC Hausen am Albis',
  'FC Haute-Ajoie',
  'FC Haute-Gruyère',
  'FC Hebar Pazardzhik',
  'FC Hegelmann',
  'FC Hellas Kagran',
  'FC Helsingør',
  'FC Hennef 05',
  'FC Hermannstadt',
  'FC Hertha Wels',
  'FC Hirnyk-Sport',
  'FC Honka Espoo',
  'FC Hoverla Uzhhorod (1946-2016)',
  'FC Hradec Králové',
  'FC Höchst',
  'FC Ibach',
  'FC Iberia 1999 Tbilisi',
  'FC Ilves',
  'FC Ingolstadt 04',
  'FC Inter Turku',
  'FC Internazionale Milano',
  'FC Irtysh Pavlodar',
  'FC Iskra-Stal',
  'FC Isloch',
  'FC Istres',
  'FC Jazz',
  'FC Jokerit (1999-2004)',
  'FC Juniors OÖ',
  'FC Juárez',
  'FC Kafr Qasim',
  'FC Kairat Almaty',
  'FC Kamza',
  'FC Karpaty Lviv',
  'FC Kaysar Kyzylorda',
  'FC Khimki',
  'FC Kickers Luzern',
  'FC Kitzbühel',
  'FC Kolkheti Poti',
  'FC Koper',
  'FC Košice',
  'FC Krasnodar',
  'FC Kreuzlingen',
  'FC Krumovgrad',
  'FC Kryvbas Kryvyi Rih',
  'FC Kuban',
  'FC Kuban Krasnodar',
  'FC Kufstein',
  'FC Kuressaare',
  'FC Kuusysi',
  'FC Kyzylzhar Petropavlovsk',
  'FC Köniz',
  'FC København',
  'FC La Chaux-de-Fonds',
  'FC Lachen/Altendorf',
  'FC Lahti',
  'FC Lancy',
  'FC Langenegg',
  'FC Langenthal',
  'FC Lankowitz',
  'FC Lantana Tallinn (1994-1999)',
  'FC Laufen',
  'FC Lausanne',
  'FC Lausanne-Sport',
  'FC Lauterach',
  'FC Le Mont',
  'FC Lendorf',
  'FC LeRK Brno (1910-1995)',
  'FC Levadia Tallinn',
  'FC Libourne-Saint-Seurin',
  'FC Liefering',
  'FC Linth 04',
  'FC Littau',
  'FC Locarno',
  'FC Locomotive Tbilisi',
  'FC Lokomotiv Moscow',
  'FC Lokomotíva Košice',
  'FC Lorient',
  'FC Lugano',
  'FC Lusitans',
  'FC Lustenau 07',
  'FC Luzern',
  'FC Lviv',
  'FC Magpies',
  'FC Marchfeld',
  'FC Margveti Zestafoni (1990-2000)',
  'FC Mariupol',
  'FC Martigues',
  'FC Mauerwerk',
  'FC Mecklenburg Schwerin',
  'FC Memmingen',
  'FC Mendrisio',
  'FC Metalist Kharkiv',
  'FC Metalurgi Rustavi',
  'FC Metalurh Donetsk',
  'FC Metalurh Zaporizhya',
  'FC Metz',
  'FC Meyrin',
  'FC Midtjylland',
  'FC Mika',
  'FC Milsami Orhei',
  'FC Minsk',
  'FC Mondercange',
  'FC Monthey',
  'FC Mordovia',
  'FC Moscow',
  'FC Moskva',
  'FC Motagua',
  'FC Motown',
  'FC Mulhouse',
  'FC Mulhouse Portland',
  'FC Muri',
  'FC Mynai',
  'FC Münsingen',
  'FC Naftan Novopolotsk',
  'FC Nantes',
  'FC Neman Grodno',
  'FC Nistru Otaci',
  'FC Nitra',
  'FC Noah',
  'FC Nordsjælland',
  'FC Norma Tallinn (1959-1997)',
  'FC Nõmme United',
  'FC Nöttingen',
  'FC Oberneuland',
  'FC Obolon Kyiv',
  'FC Okzhetpes Kokshetau',
  'FC Olexandriya',
  'FC Olimpia Balti',
  'FC Olimpik Donetsk',
  'FC Olympique',
  'FC Onex',
  'FC Ordabasy Shymkent',
  'FC Ordino',
  'FC Orenburg',
  'FC Oss',
  'FC Paradiso',
  'FC Partizan Minsk',
  'FC Pas de la Casa',
  'FC Pasching',
  'FC Paços de Ferreira',
  'FC Penafiel',
  'FC Petrolul Ploiești',
  'FC Petržalka',
  'FC Pinzgau Saalfelden',
  'FC Pipinsried',
  'FC Pirin Blagoevgrad',
  'FC Politehnica Iași',
  'FC Porrentruy',
  'FC Portalban/Gletterens',
  'FC Porto',
  'FC Printse-Nendaz',
  'FC Prishtina',
  'FC Prishtina Bern',
  'FC Progrès Niederkorn',
  'FC PTT Rayong',
  'FC Pyunik',
  'FC Rapperswil-Jona',
  'FC RB Salzburg',
  'FC Red Bull Salzburg',
  'FC Red Star Zürich',
  'FC Regensdorf',
  'FC Reipas Lahti',
  'FC Rodange 91',
  'FC Rohrendorf/Gedersdorf',
  'FC Rorschach',
  'FC Roskilde',
  'FC Rostov',
  'FC Rot-Weiß Erfurt',
  'FC Rotkreuz',
  'FC Rouen',
  'FC Rubin Kazan',
  'FC Rukh Lviv',
  'FC Ryukyu',
  "FC Rànger's",
  'FC Sachsen Leipzig (1990-2011)',
  'FC Saint-Blaise',
  'FC Saint-Prex',
  'FC Samgurali',
  'FC Samtredia',
  'FC Santa Coloma',
  'FC Santos Tartu',
  'FC Saturn Ramenskoye',
  'FC Savièse',
  'FC Saxan',
  'FC Saxon Sports',
  'FC Schaffhausen',
  'FC Schalke 04',
  'FC Schattdorf',
  'FC Schoenberg',
  'FC Schwarzach',
  'FC Schönberg 95',
  'FC Schönenwerd-Niedergösgen',
  'FC Schötz',
  'FC Sellier & Bellot Vlašim',
  'FC Senec (1994-2008)',
  'FC Seoul',
  'FC Septemvri Sofia',
  'FC Seuzach',
  'FC Sevastopol (2002-2014)',
  'FC Severin',
  'FC Sfintul Gheorghe Suruceni',
  'FC Shakhtar Donetsk',
  'FC Shakhter Karagandy',
  'FC Shakhtyor Soligorsk',
  'FC Sheriff Tiraspol',
  'FC Shirak',
  'FC Shumen 1929 (-2016)',
  'FC Sibir Novosibirsk',
  'FC Sierre',
  'FC Silon Táborsko',
  'FC Sion',
  'FC Sioni Bolnisi',
  'FC Sirens',
  'FC Slavia-Mozyr',
  'FC Sliven (-2000)',
  'FC Slovan Liberec',
  'FC Smorgon',
  'FC Sochaux-Montbéliard',
  'FC Solothurn',
  'FC Someo',
  'FC Sopron (1921-2008)',
  'FC Spartak Moscow',
  'FC Spartak Moskva',
  'FC Spartak Trnava',
  'FC Spartak Varna',
  'FC Spartans',
  'FC Speranța Nisporeni',
  'FC St. Gallen',
  'FC St. Pauli',
  'FC St. Veit',
  'FC St.-Leonard',
  'FC Stade Nyonnais',
  'FC Stadlau',
  'FC Stahl Brandenburg',
  'FC Stahl Linz',
  'FC Stal Kamianske (1926-2018)',
  'FC Sternenberg',
  'FC Stockholm Inter',
  'FC Struga',
  'FC Stumbras',
  'FC Subingen',
  'FC Suhareka',
  'FC Suhr',
  'FC Suðuroy',
  'FC Swift Hesperange',
  'FC Sète',
  'FC Südtirol',
  'FC Tambov',
  'FC Taraz',
  'FC Tatabánya',
  'FC Tekstilshchik Ivanovo',
  'FC Tekstilshchik Kamyshin',
  'FC Telavi',
  'FC Terek Grozny',
  'FC Teutonia 05',
  'FC Thun',
  'FC Tirsense',
  'FC Tobol Kostanay',
  'FC Tokyo',
  'FC Tom Tomsk',
  'FC Torpedo Kutaisi',
  'FC Torpedo Moscow',
  'FC Torpedo Zhodino',
  'FC Torpedo-SKA Minsk',
  'FC Trollhättan',
  'FC Tskhinvali',
  'FC Tuggen',
  'FC Tulsa',
  'FC TVMK Tallinn',
  'FC Twente',
  'FC Ufa',
  'FC UNA Strassen',
  'FC Union Titus Pétange',
  'FC Unterstrass',
  'FC Ural Yekaterinburg',
  'FC Urartu',
  'FC Ursy',
  'FC USV Eschen/Mauren ### check if plays in swiss leagues (3rd league promotion - if yes',
  'FC Utrecht',
  'FC Vaduz',
  'FC Van',
  'FC Vaslui',
  'FC Veris (2011-2014)',
  'FC Versailles',
  'FC Vestsjælland',
  'FC Victoria Brănești (1968-2012)',
  'FC Victoria Rosport',
  'FC Viitorul Constanța (2009-2021)',
  'FC Viktoria 1889 Berlin',
  'FC Viktoria Köln',
  'FC Viktoria Plzeň',
  'FC Vilaverdense',
  'FC Villefranche',
  'FC ViOn Zlaté Moravce',
  'FC Vitebsk',
  'FC Vizela',
  'FC Volendam',
  'FC Voluntari',
  'FC Volyn Lutsk',
  'FC Vorskla Poltava',
  'FC VSS Košice (1952-2017)',
  'FC Vysočina Jihlava',
  'FC Wacker Innsbruck',
  'FC Wacker Innsbruck (2002)',
  'FC Wallbach',
  'FC Wels',
  'FC Wettingen',
  'FC Wettswil-Bonstetten',
  'FC Widnau',
  'FC Wiedikon ZH',
  'FC Wil',
  'FC Wiltz 71',
  'FC Winkeln SG',
  'FC Winkeln St. Gallen',
  'FC Winterthur',
  'FC WIT Georgia',
  'FC Wittenbach',
  'FC Wohlen',
  'FC Wolfurt',
  'FC Yenisey Krasnoyarsk',
  'FC Yerevan',
  'FC Zaria Balti',
  'FC Zbrojovka Brno',
  'FC Zell am See',
  'FC Zenit Saint Petersburg',
  'FC Zestafoni',
  'FC Zhetysu Taldykorgan',
  'FC Zimbru Chișinău',
  'FC Zirka Kropyvnytskyi',
  'FC Zirl',
  'FC Zlín',
  'FC Zollbrück',
  'FC Zorya Luhansk',
  'FC Zvezda-BGU Minsk',
  'FC Zürich',
  'FC Šiauliai (1995-2016)',
  'FC-Astoria Walldorf',
  'FCI Tallinn',
  'FCM Bacău',
  'FCM Traiskirchen',
  'FCO Charleville',
  'FCV Dender EH',
  'FCV Farul Constanța',
  'Felipe Villanueva No. 300 1er piso',
  'Fenerbahçe İstanbul',
  'Fenerbahçe S.K. (football)',
  'Feralpisalò',
  'Ferencvárosi TC',
  'Ferro Carril Oeste',
  'Feyenoord',
  'Feyenoord Rotterdam',
  'FF Jaro',
  'FFC Victoria 91',
  'FH Hafnarfjörður',
  'Figueirense',
  'Figueirense FC',
  'Finn Harps FC',
  'Finnairin Palloilijat Helsinki (1965-1998)',
  'First Vienna FC',
  'Fischhofgasse 12 // 1100 Wien',
  'Fjölnir Reykjavík',
  'FK Arsenal Tivat',
  'FK Atlantas',
  'FK Auda Riga',
  'FK Austria Wien',
  'FK Banat Zrenjanin (2006-2016)',
  'FK Banga',
  'FK Baník Sokolov',
  'FK Bashkimi Kumanovo (1947-2008)',
  'FK Belasica',
  'FK Bežanija',
  'FK Bokelj',
  'FK Borac Banja Luka',
  'FK Borac Čačak',
  'FK Borec Veles',
  'FK Budućnost Banovići',
  'FK Budućnost Podgorica',
  'FK Bylis',
  'FK Cementarnica 55',
  'FK Csíkszereda Miercurea Ciuc',
  'FK Dečić',
  'FK Drnovice (1932-2006)',
  'FK Dukla Prague',
  'FK Dukla Praha',
  'FK Dynamo Makhachkala',
  'FK Ekranas',
  'FK Hajduk Kula (1925-2013)',
  'FK Haugesund',
  'FK Humenné',
  'FK Igman Konjic',
  'FK Indjija',
  'FK Inkaras Kaunas (1937-2003)',
  'FK Inter Bratislava',
  'FK Iskra',
  'FK Jablonec',
  'FK Jagodina',
  'FK Javor Ivanjica',
  'FK Jedinstvo Bijelo Polje',
  'FK Jedinstvo Ub',
  'FK Jelgava',
  'FK Jerv',
  'FK Jezero',
  'FK Kareda Kaunas (1935-2003)',
  'FK Kauno Žalgiris',
  'FK Kom',
  'FK Kruoja',
  'FK Kukësi',
  'FK Leotar',
  'FK Liepāja',
  'FK Livyi Bereh',
  'FK Lovćen',
  'FK LU/Daugava (1979-2000)',
  'FK Makedonija Skopje',
  'FK Mažeikiai',
  'FK Metalurg Skopje',
  'FK Milano',
  'FK MKT Araz',
  'FK Mladost Doboj Kakanj',
  'FK Mladost Lučani',
  'FK Mladá Boleslav',
  'FK Modriča',
  'FK Mogren (1920-2016)',
  'FK Mornar',
  'FK Napredak',
  'FK Novi Beograd',
  'FK Novi Pazar',
  'FK Obilić (1924-2015)',
  'FK Olimpic Sarajevo ## check if same as FK Sarajevo ??',
  'FK Otrant',
  'FK Palanga',
  'FK Pardubice',
  'FK Partizan Belgrade',
  'FK Partizani Tirana',
  'FK Pelister',
  'FK Pirmasens',
  'FK Pobeda',
  'FK Podgorica',
  'FK Pohronie',
  'FK Poprad',
  'FK Proleter',
  'FK Proleter Novi Sad',
  'FK Příbram',
  'FK Rabotnički',
  'FK Rad Belgrade',
  'FK Radnik Bijeljina',
  'FK Radnik Surdulica',
  'FK Radnički',
  'FK Radnički Niš',
  'FK Renova',
  'FK RFS',
  'FK Riteriai',
  'FK Rudar Pljevlja',
  'FK Sarajevo',
  'FK Senica',
  'FK Sevojno (1950-2010)',
  'FK Shafa Baku (1997-2005)',
  'FK Shkëndija 79',
  'FK Sileks',
  'FK Slavija Sarajevo',
  'FK Slavoj Vyšehrad',
  'FK Sloboda Tuzla',
  'FK Sloboda Užice',
  'FK Sloga Doboj',
  'FK Smederevo',
  'FK Spartak Subotica',
  'FK Spartak Zlatibor Voda',
  'FK Spartaks Jūrmala',
  'FK Sutjeska',
  'FK Sūduva',
  'FK Tauras',
  'FK Tekstilac Odžaci',
  'FK Teplice',
  'FK Teteks',
  'FK TransINVEST',
  'FK Tukums',
  'FK Turan Turkistan',
  'FK Turnovo',
  'FK Tuzla City',
  'FK Třinec',
  'FK Valmiera',
  'FK Vardar',
  'FK Varnsdorf',
  'FK Ventspils',
  'FK Viktoria Žižkov',
  'FK Vojvodina',
  'FK Voždovac',
  'FK Vėtra',
  'FK Yelimay Semey',
  'FK Zeta',
  'FK Zhenys',
  'FK Ústí nad Labem',
  'FK Čelik Nikšić',
  'FK Čukarički',
  'FK Şamaxı',
  'FK Şämkir (1954-2017)',
  'FK Železiarne Podbrezová',
  'FK Železničar Pančevo',
  'FK Željezničar',
  'Flamengo RJ',
  'Flamurtari Prishtina',
  'Flamurtari Vlorë',
  'Fleetwood Town F.C.',
  'Fleetwood Town FC',
  'Flint Town United FC',
  'Floriana FC',
  'Florida Soccer Soldiers',
  'Floridsdorfer AC',
  'Fluminense FC',
  'Fluminense RJ',
  'Forest Green Rovers F.C.',
  'Forest Green Rovers FC',
  'Forfar Athletic',
  'Forge FC',
  'Fortaleza EC',
  'Fortaleza Esporte Clube',
  'Fortaleza FC',
  'Fortuna Düsseldorf',
  'Fortuna Köln',
  'Fortuna Sittard',
  'Forward Madison FC',
  'Fram Reykjavík',
  'Francisco I. Madero No.',
  'Franz-Böhmert-Straße 1c // 28205 Bremen',
  'Franz-Kremer-Allee 1 // 50937 Köln',
  'Fredrikstad FK',
  'Fresno FC',
  'Frigg Oslo FK',
  'Fritz-Walter-Str. 1 // 67663 Kaiserslautern',
  'Frosinone Calcio',
  'FS Jelgava',
  'FS La Massana',
  'FS METTA',
  'FSC Lori',
  'FSV Frankfurt',
  'FSV Optik Rathenow',
  'FSV Salmrohr',
  'FSV Zwickau',
  'FT Braunschweig',
  'Fuerza Amarilla SC',
  'Fujieda MYFC',
  'Fulham F.C.',
  'Fulham FC',
  'FUS Rabat',
  'FV Austria XIII',
  'FV Engers 07',
  'FV Illertissen',
  'FV Ravensburg',
  'Fylkir Reykjavik',
  'G.D. Chaves',
  'Gabala SC',
  'Gainsborough Trinity FC',
  'GAIS',
  'Galatasaray İstanbul',
  'Galatasaray S.K. (football)',
  'Galeana',
  'Gallipoli Football SSD',
  'Galway United FC',
  'Gamba Osaka',
  'Gangwon FC',
  'Gateshead FC',
  'Gaz Metan Mediaș',
  'Gaziantepspor',
  'Gazişehir Gaziantep FK',
  'Gazélec Ajaccio',
  'GD Chaves',
  'Gefle IF',
  'General Caballero (JLM)',
  'Genoa C.F.C.',
  'Genoa CFC',
  'Gençlerbirliği Ankara SK',
  'Germania Egestorf/Langreder',
  'Germinal Beerschot (1920-2013)',
  'Getafe CF',
  'GFC Ajaccio',
  'GFK Tikvesh',
  'Ghazl El Mahalla',
  'Giana Erminio',
  'Gibraltar Phoenix FC',
  'GIF Sundsvall',
  'Gil Vicente FC',
  'Gillingham F.C.',
  'Gillingham FC',
  'Giltschwertgasse 81 // 2700 Wr. Neustadt',
  'Gimnasia y Esgrima de Jujuy',
  'Gimnasia y Esgrima de Mendoza',
  'Gimnasia y Esgrima LP',
  'Gimnasia y Tiro',
  'Gimnàstic Tarragona',
  'Gimnástica Segoviana',
  'Giravanz Kitakyushu',
  'Giresunspor',
  'Girona FC',
  'Girondins de Bordeaux',
  'GKS Bełchatów',
  'GKS Katowice',
  'GKS Tychy',
  'Glacis United FC',
  'Glenavon FC',
  'Glentoran FC',
  'Gloria Bistrița',
  'Glossop North End AFC',
  'Gloucestershire',
  'GNK Dinamo Zagreb',
  'Go Ahead Eagles',
  'GOAL FC',
  'Godoy Cruz',
  'Godoy Cruz Antonio Tomba',
  'Goiás EC',
  'Goiás Esporte Clube',
  'Golden Arrows',
  'Golden State Force',
  'Granada 74',
  'Granada CF',
  'Grasshopper Club Zürich',
  'Grasshoppers Zürich',
  'Grays Athletic FC',
  'Grazer AK',
  'Greater London | London',
  'Greater Manchester | Manchester',
  'Greenock Morton',
  'Greenville Triumph',
  'Greifswalder FC',
  'Grenoble Foot 38',
  'Gretna F.C.',
  'Gretna FC',
  'Grimsby Town F.C.',
  'Grimsby Town FC',
  'Grindavík',
  'Grobiņas SC',
  'Grêmio Barueri',
  'Grêmio Esportivo Brasil',
  'Grêmio Foot-Ball Porto Alegrense',
  'Grêmio Novorizontino',
  'Grêmio RS',
  'Grótta',
  'Grünwalder Straße 114 // 81547 München',
  'Guadalajara Chivas',
  'Guadalupe FC',
  'Guaireña FC',
  'Guangzhou City FC (2011-2023)',
  'Guangzhou Evergrande Taobao F.C.',
  'Guangzhou FC',
  'Guangzhou R&F',
  'Guarani FC',
  'Guayaquil City FC',
  'Gudja United',
  'Guillermo Brown',
  'Guiseley AFC',
  'Guizhou Hengfeng',
  'Guizhou Hengfeng Zhicheng F.C.',
  'GV San José',
  'Gwangju FC',
  'Gwardia Warszawa',
  'Gyeongnam FC',
  'Gyirmót FC Győr',
  'Győri ETO FC',
  'GÍ Gøta (1926-2008)',
  'Górnik Zabrze',
  'Górnik Łęczna',
  'Göztepe İzmir',
  'Göztepe S.K.',
  'Gütersloh',
  'Gżira United FC',
  'Hacettepespor',
  'Hainaut',
  'Hainaut › Wallonie | Hainaut',
  'Hallescher FC',
  'Halmstads BK',
  'Hamarkameratene',
  'Hamburg',
  'Hamburger Straße 210 // 38112 Braunschweig',
  'Hamburger SV',
  'Hamilton Academical F.C.',
  'Hamilton Academical FC',
  'Hamilton Accies',
  'Hamilton Wanderers',
  'Hammarby IF',
  'Hammarby Talang FF',
  'Hampshire',
  'Hampton & Richmond Borough FC',
  'Hamrun Spartans FC',
  'Hannover 96',
  'Hanns-Braun-Straße / Friesenhaus 2 // 14053 Berlin',
  'Hansa Rostock',
  'Hanácká Slávia Kroměříž',
  'Hapoel Acre FC',
  'Hapoel Afula FC',
  'Hapoel Ashkelon FC',
  "Hapoel Be'er Sheva F.C.",
  'Hapoel Beer-Sheva FC',
  'Hapoel Bnei Lod FC',
  'Hapoel Hadera F.C.',
  'Hapoel Hadera FC',
  'Hapoel Haifa F.C.',
  'Hapoel Haifa FC',
  'Hapoel Herzliya',
  'Hapoel Iksal',
  'Hapoel Ironi Kiryat Shmona F.C.',
  'Hapoel Jerusalem',
  'Hapoel Kfar Shalem',
  'Hapoel Kfar-Saba FC',
  'Hapoel Kiryat Shmona FC',
  'Hapoel Marmorek',
  'Hapoel Nof HaGalil FC',
  'Hapoel Petah Tikva FC',
  "Hapoel Ra'anana A.F.C.",
  "Hapoel Ra'anana AFC",
  "Hapoel Ramat Gan Giv'atayim FC",
  'Hapoel Ramat HaSharon FC',
  'Hapoel Rishon LeZion FC',
  'Hapoel Tel Aviv F.C.',
  'Hapoel Tel-Aviv FC',
  'Hapoel Umm al-Fahm FC',
  'Haras El Hodood',
  'Harbour View',
  'Haringey Borough FC',
  'Harrogate Town AFC',
  'Hartford Athletic',
  'Hartlepool United FC',
  'Hatayspor',
  'Hatta Club',
  'Havant & Waterlooville FC',
  'Haverfordwest County AFC',
  "Hawke's Bay United",
  'Hayes & Yeading United FC',
  'HB Køge',
  'HB Tórshavn',
  'Heart of Midlothian F.C.',
  'Heart of Midlothian FC',
  'Hebei China Fortune',
  'Hebei China Fortune F.C.',
  'Heiligengeistfeld 1 // 20359 Hamburg',
  'Hellas Verona',
  'Hellerup IK',
  'Helmond Sport',
  'Helsingborgs IF',
  'Henan Jianye',
  'Hennes-Weisweiler-Allee 1 // 41179 Mönchengladbach',
  'Heracles Almelo',
  'Heredia Jaguares de Peten',
  'Hereford FC (2014-)',
  'Hereford United FC (1924-2014)',
  'Herefordshire',
  'Herfølge BK (1921-2009)',
  'Hertfordshire',
  'Hertha BSC',
  'Hessen',
  'HFC Haarlem (1889-2010)',
  'HFX Wanderers',
  'Hibernian F.C.',
  'Hibernian FC',
  'Hibernians FC',
  'HIFK Helsinki',
  'Highlands Park',
  'Hillerød Fodbold',
  'Histon FC',
  'Hitchin Town FC',
  'HJK Helsinki',
  'HK Kópavogs',
  'HNK Cibalia',
  'HNK Gorica',
  'HNK Hajduk Split',
  'HNK Orašje',
  'HNK Orijent',
  'HNK Rijeka',
  'HNK Vukovar',
  'HNK Šibenik',
  'Hobro IK',
  'Hokkaido Consadole Sapporo',
  'Holbæk B&I',
  'Holstein Kiel',
  'Honda FC',
  'Horrenberger Straße 58 // 74939 Zuzenhausen ## check for Hoffenheim ??',
  'Houang United FC',
  'Houston Dynamo',
  'HPS Helsinki',
  'HSC Montpellier',
  'HSV Barmbek-Uhlenhorst',
  'Huddersfield Town A.F.C.',
  'Huddersfield Town AFC',
  'Hull City',
  'Hull City A.F.C.',
  'Hull City AFC',
  'Humble Lion',
  'Huracán',
  'Huracán Corrientes',
  'Huracán de Tres Arroyos',
  'HUS Agadir',
  'Husqvarna FF',
  'Hutnik Kraków',
  'Hvidovre IF',
  'Hyde United FC',
  'Hércules CF',
  'Hønefoss BK',
  'HŠK Zrinjski',
  'I. Metapán',
  'IF Brommapojkarna',
  'IF Elfsborg',
  'IF Gnistan',
  'IF Karlstad Fotbol',
  'IFK Göteborg',
  'IFK Malmö',
  'IFK Mariehamn',
  'IFK Norrköping',
  'IFK Stocksund',
  'IFK Värnamo',
  "Ihud Bnei Shefa-'Amr",
  'Ihud Shefa-AMR',
  'ii) 1. FC Nürnberg II',
  'ii) 1. FSV Mainz 05 II',
  'ii) AC Sparta Praha B',
  'ii) Athletic Club Bilbao B',
  'ii) Atlanta United 2',
  'ii) Atlético Madrid B',
  'ii) Austria Lustenau Amateure',
  'ii) AZ Alkmaar II',
  'ii) Bayern München II',
  'ii) Borussia Dortmund II',
  'ii) BSC Young Boys II',
  'ii) FC Admira Wacker Mödling II',
  'ii) FC Augsburg II',
  'ii) FC Barcelona B',
  'ii) FC Basel II',
  'ii) FC Krasnodar 2',
  'ii) FC Luzern II',
  'ii) FC Porto B',
  'ii) FC RB Salzburg II ## check for old name until season 2011/12 - now "independent" Liefering?',
  'ii) FC Wacker Innsbruck II',
  'ii) FC Zürich II',
  'ii) Hannover 96 II',
  'ii) Horn Amateure',
  'ii) Jong Ajax',
  'ii) Jong FC Utrecht',
  'ii) Jong PSV',
  'ii) Kapfenberger SV II',
  'ii) LA Galaxy II',
  'ii) LASK Amateure OÖ',
  'ii) Málaga CF B',
  'ii) New York Red Bulls II ## Montclair',
  'ii) Philadelphia Union II',
  'ii) Portland Timbers 2',
  'ii) RCD Mallorca B',
  'ii) Real Madrid B',
  'ii) Real Sociedad B',
  'ii) SC Freiburg II',
  'ii) SCR Altach Juniors',
  'ii) Sevilla FC B',
  'ii) Shamrock Rovers II',
  'ii) Sigma Olomouc B',
  'ii) SK Rapid Wien II',
  'ii) SK Sturm Graz II',
  'ii) SKN St. Pölten Juniors',
  'ii) SL Benfica B',
  'ii) South Georgia Tormenta 2',
  'ii) Spartak Moskva II',
  'ii) Sporting Kansas City II',
  'ii) SpVgg Greuther Fürth II',
  'ii) St. Gallen A.',
  'ii) SV Grödig II',
  'ii) SV Mattersburg II',
  'ii) SV Ried II',
  'ii) VfB Stuttgart II',
  'ii) Villarreal CF B',
  'ii) Wellington Phoenix Reserves ## reserve team plays in championship',
  'ii) Werder Bremen II',
  'ii) Wolfsberger AC II',
  'ii) WSG Tirol Amateure',
  'ii) Young Violets Austria Wien',
  'IK Brage',
  'IK Frej',
  'IK Oddevold',
  'IK Sirius',
  'IK Start',
  'Ikast FS (1935-1999)',
  'IL Hødd',
  'Iliria Solothurn',
  'Ilves-Kissat Tampere',
  'Imbabura',
  'In den Allerwiesen 1 // 38446 Wolfsburg',
  'Incheon United',
  'Independiente del Valle',
  'Independiente Medellín',
  'Independiente Petrolero',
  'Independiente Rivadavia',
  'Independiente Santa Fe',
  'Indios de Ciudad Juarez (2005-2011)',
  'Indy Eleven',
  'Inhulets Petrove',
  'Institute FC',
  'Instituto',
  "Inter Club d'Escaldes",
  'Inter Miami CF',
  'Inter Milan',
  'Internacional de Palmira',
  'Internacional Porto Alegre',
  'Inverness Caledonian Thistle',
  'Inverness Caledonian Thistle F.C.',
  'Inverness CT',
  'Ionikos FC',
  'Ipatinga Futebol Clube',
  'Ipswich Town F.C.',
  'Ipswich Town FC',
  'IR Tanger',
  'Iraklis 1908 Thessaloniki FC',
  'Ironi Tiberias',
  'Isaac-Fulda-Allee 5 // 55124 Mainz',
  'Ismaily',
  'Italien Pertandingan',
  'Ittihad El Shorta',
  'Ituano FC SP',
  'Iwaki FC',
  'Iwate Grulla Morioka',
  'İnter Bakı PİK',
  'İstanbul Başakşehir',
  'İstanbul Başakşehir F.K.',
  'İstanbulspor',
  'Jagiellonia Białystok',
  'Jaguares Chiapas',
  'Jaguares de Chiapas',
  'Jaguares de Córdoba',
  'Jahnstraße 1 // 69207 Sandhausen',
  'Jamshedpur',
  'JEF United Chiba',
  'Jeju United',
  'Jeonbuk Motors',
  "Jeunesse d'Esch",
  'Jiangsu Suning',
  'Jiangsu Suning F.C.',
  'JIPPO Joensuu',
  'JJK Jyväskylä',
  'JK Nõmme Kalju',
  'JK Sillamäe Kalev',
  'JK Tallinna Kalev',
  'JK Tammeka Tartu',
  'JK Trans Narva',
  'JK Tulevik Viljandi',
  'Johann Steinböck Strasse 5b // 2344 Maria Enzersdorf ## Mödling',
  'Joinville EC',
  'JS Kairouanaise',
  'JS Soualem',
  'Juan Aurich',
  'Junior de Barranquilla',
  'Juventud de Las Piedras',
  'Juventus',
  'Juventus F.C.',
  'Järvenpään Palloseura',
  'Jönköpings Södra IF',
  'Júbilo Iwata',
  'K Heusden-Zolder',
  'K Lierse SK',
  'K. Beerschot VA',
  'K. Sint-Truidense VV',
  'K.A.A. Gent',
  'K.A.S. Eupen',
  'K.R.C. Genk',
  'K.S.C. Lokeren Oost-Vlaanderen',
  'K.V. Kortrijk',
  'K.V. Oostende',
  'K.V.C. Westerlo',
  'KA Akureyri',
  'KAA Gent',
  'Kagoshima United',
  'Kaizer Chiefs',
  'Kalamata FC',
  'Kallithea FC',
  'Kalmar FF',
  'Kapfenberger SV',
  'Kaposvári Rákóczi FC',
  'Karagümrük',
  'Kardemir Karabükspor',
  'Karlsruher SC',
  'Karmiotissa Pano Polemidia',
  'Karvan FK (2004-2014)',
  'Karşıyaka SK',
  'KAS Eupen',
  'Kashima Antlers',
  'Kashima Antlers # Southwestern cities/towns of Ibaraki',
  'Kashiwa Reysol',
  'Kastoria FC',
  'Kasımpaşa İstanbul',
  'Kasımpaşa S.K.',
  'Kavala FC',
  'Kawasaki Frontale',
  'Kayseri Erciyesspor',
  'Kayserispor',
  'Kazincbarcikai SC',
  'KB København (1876-1992)',
  'Kecskeméti TE',
  'Keflavík ÍF',
  'Keisslergasse 3 // 1140 Wien',
  'Kelty Hearts FC',
  'Kent',
  'Kerkyra FC',
  'Kerry FC',
  'Kettering Town FC',
  'Keçiörengücü',
  'Keşla FK',
  'KF Apolonia',
  'KF Besa Dobërdoll',
  'KF Drenica',
  'KF Drita',
  'KF Dukagjini',
  'KF Egnatia',
  'KF Elbasani',
  'KF Ferizaj',
  'KF Feronikeli',
  'KF Gjilani',
  'KF Gostivari',
  'KF Laçi',
  'KF Llapi',
  'KF Malisheva',
  'KF Shkupi',
  'KF Skënderbeu Korçë',
  'KF Teuta Durrës',
  'KF Tirana',
  'KF Tomori',
  "KF Trepça'89",
  'KF Vllaznia',
  'KFC Komárno',
  'KFC Lommel SK',
  'KFC Uerdingen',
  'KFC Uerdingen 05',
  'KFC Verbroedering Geel',
  'KFUM-Kameratene Oslo',
  'Khazri Buzovna (1994-1998)',
  'Kickers Offenbach',
  'Kicks United FC',
  'Kidderminster Harriers FC',
  'Kilikia FC (1992-2011)',
  'Kilmarnock F.C.',
  'Kilmarnock FC',
  "King's Lynn FC",
  'Kingstonian FC',
  'Kisvárda FC',
  'KKS Lech Poznań',
  'Klubi 04',
  'KMSK Deinze',
  'Knattspyrnufélag Fjallabyggðar',
  'Knockbreda FC',
  'Kocaelispor',
  'Kolding IF',
  'Kolos Kovalivka',
  'Komlói Bányász SK',
  'Kongsvinger IL',
  'Konyaspor',
  'Koparit Kuopio (1931-1990)',
  'Korona Kielce',
  'KPV Kokkola',
  'KR Reykjavík',
  'KRC Genk',
  'KRC Harelbeke',
  'Kristiansund BK',
  'KS Besa',
  'KS Cracovia',
  'KS Flamurtari',
  'KS Kastrioti',
  'KS Luftëtari',
  'KS Skënderbeu',
  'KS Teuta',
  'KS Wisła Puławy',
  'KS_Cracovia_(football)',
  'KSC Lokeren OV',
  'KSK Beveren',
  'KSP Polonia Warszawa',
  'KSV Baunatal',
  'KSV Hessen Kassel',
  'KSV Roeselare',
  'KSV Waregem (1925-2001)',
  'KTP Kotka',
  'KuPS Kuopio',
  'KV Kortrijk',
  'KV Mechelen',
  'KV Oostende',
  'KVC Westerlo',
  'Kyoto Sanga',
  'KäPa',
  'Käpäz PFK',
  'Kärnten',
  'KÍ Klaksvík',
  'Køge BK (1927-2009)',
  'La Equidad',
  'LA Galaxy',
  'La Luz FC',
  'La Paz FC (1989-2013)',
  'Lakeland Tropics',
  'LALA FC',
  'Lancashire',
  'Landskrona BoIS',
  'Lansing Ignite FC',
  'Laredo Heat',
  'Larne FC',
  'Las Vegas Lights FC',
  'LASK Linz',
  'Laubenweg 60 // 90765 Fürth',
  'LB Châteauroux',
  'LD Alajuelense',
  'LDU Loja',
  'LDU Quito',
  'Le Havre AC',
  'Le Locle Sports',
  'Le Mans FC',
  'Le Puy',
  'Lechia Gdańsk',
  'Leeds City FC (1904-1919)',
  'Leeds United F.C.',
  'Leeds United FC',
  'Legia Warszawa',
  'Leicester City',
  'Leicester City F.C.',
  'Leicester City FC',
  'Leicestershire',
  'Leiknir Reykjavík',
  'Leixões SC',
  'Lennéstraße 12 // 01069 Dresden',
  'Leones FC',
  'Leones Negros U. de G.',
  'Levadiakos FC',
  'Levanger FK',
  'Levante UD',
  'Lewes FC',
  'Leyton Orient FC',
  'Leça FC',
  'Liaoning FC',
  'Libertad',
  'Libertad Ascunción',
  'Libramiento Circuito de la Concepción km 2 s/n',
  'Lille OSC',
  'Lillestrøm SK',
  'Limburg',
  'Limburg › Vlaanderen | Limburg',
  'Lime Hall Academy',
  'Limerick FC (1937-2020)',
  'Limón FC',
  'Lincoln City F.C.',
  'Lincoln City FC',
  'Lincoln FC',
  'Lincolnshire',
  'Linfield FC',
  'Lions Gibraltar FC',
  'Lisburn Distillery FC',
  'Little Rock Rangers',
  'Liverpool & Merseyside | Merseyside ## note: added Liverpool & - why? why not?',
  'Liverpool F.C.',
  'Liverpool FC',
  'Liverpool Montevideo',
  'Livingston F.C.',
  'Livingston FC',
  'Liège',
  'Liège › Wallonie | Liège',
  'Ljungskile SK',
  'Llandudno FC',
  'Llanelli AFC',
  'Llaneros FC',
  'Llaneros Guanare',
  'Lleida Esportiu',
  'LNZ Cherkasy',
  'Lobos BUAP',
  'Lokomotiv Moscow',
  'Lokomotiv Moskva',
  'Lommel United',
  'London, Greater',
  'Londrina EC',
  'Londrina Esporte Clube',
  'Longford Town FC',
  'Lorca FC',
  'Lorca FC (2003-2022)',
  'Los Angeles FC',
  'Los Angeles FC ## Los_Angeles_Football_Club',
  'Los Angeles Galaxy',
  'Los Chankas',
  'LOSC Lille',
  'Loudoun United FC',
  'Loughborough FC (1886-1900)',
  'Loughgall FC',
  'Louisville City FC',
  'LR Vicenza Virtus',
  'LTS Bremerhaven',
  'Luch Energia Vladivostok',
  'Luftëtari Gjirokastër FC',
  'Luis Ángel Firpo',
  'Lunds BK',
  'Luton Town F.C.',
  'Luton Town FC',
  'Luverdense EC',
  'Lyn Oslo',
  'Lyngby BK',
  'Lynx FC',
  'Lößnitzer Straße 95 // 08280 Aue',
  'Lüneburger SK Hansa',
  'MA Tétouan',
  'Maardu Esteve',
  'Maccabi Ahi Nazareth FC',
  'Maccabi Bnei',
  'Maccabi Haifa F.C.',
  'Maccabi Haifa FC',
  'Maccabi Herzliya',
  'Maccabi Ironi Ashdod',
  'Maccabi Ironi Kiryat Ata',
  'Maccabi Jaffa',
  'Maccabi Kabilio Jaffa',
  'Maccabi Netanya F.C.',
  'Maccabi Netanya FC',
  'Maccabi Petah Tikva F.C.',
  'Maccabi Petah Tikva FC',
  'Maccabi Tel Aviv F.C.',
  'Maccabi Tel-Aviv FC',
  'Maccabi Yavne',
  'Macclesfield Town F.C.',
  'Macclesfield Town FC',
  'Machida Zelvia',
  'Macva Sabac',
  'Maidenhead United FC',
  'Maidstone United FC',
  'Malatyaspor',
  'Maldon & Tiptree FC',
  'Malmö FF',
  'Mamelodi Sundowns',
  'Manchester 62 FC',
  'Manchester City',
  'Manchester City F.C.',
  'Manchester City FC',
  'Manchester United',
  'Manchester United F.C.',
  'Manchester United FC',
  'Manchester, Greater',
  'Manisa',
  'Manisaspor',
  'Mansfield Town F.C.',
  'Mansfield Town FC',
  'Mantova SSD',
  'Marignane GCB',
  'Maritzburg United',
  'Marsa FC',
  'Marsaxlokk FC',
  'MAS Fès',
  'Matsumoto Yamaga',
  'Mazatlán FC',
  'MC Fermana FC',
  'MC Oujda',
  'Mecklenburg-Vorpommern',
  'Meizhou Hakka FC',
  'Melanchthonstraße 31a // 33615 Bielefeld',
  'Melbourne City FC',
  'Melbourne Victory',
  'Melita FC',
  'Memphis 901 FC',
  'Mendoza | Provincia Mendoza',
  'Menemenspor',
  'Mercedesstraße 109 // 70372 Stuttgart',
  'MERGE Blackpool FC',
  'MERGE Burton Swifts FC',
  'MERGE Newcastle West End FC',
  'MERGE Rotherham County FC',
  'Merseyside ## note: added Liverpool & - why? why not?',
  'Mersin İdmanyurdu',
  'Merthyr Town FC',
  'Mervue',
  'Metropolitan Police FC',
  'Metropolitanos FC',
  'Mezőkövesd Zsóry SE',
  'MFK Chrudim',
  'MFK Karviná',
  'MFK Petržalka',
  'MFK Ružomberok',
  'MFK Skalica',
  'MFK Vyškov',
  'MFK Vítkovice',
  'MFK Zemplín Michalovce',
  'Miami FC',
  'Miami Fusion',
  'Miami Fusion (1998-2001)',
  'Michael Koch Straße 50 // 7210 Mattersburg',
  'Middelfart BK',
  'Middlesbrough F.C.',
  'Middlesbrough FC',
  'Middlesbrough Ironopolis FC (1889-1894)',
  'Midland-Odessa Sockers FC',
  'Miedź Legnica',
  'Mikkelin Palloilijat',
  'Millonarios Bogotá',
  'Millwall F.C.',
  'Millwall FC',
  'Milton Keynes Dons F.C.',
  'Milton Keynes Dons FC',
  'Milwaukee Bavarian SC',
  'Mineros Zacatecas',
  'Minnesota United FC',
  'Mirassol FC SP',
  'Misiones | Provincia Misiones',
  'Misr El Makasa',
  'Mito HollyHock',
  'Mitre',
  'Mjällby AIF',
  'Mjøndalen IF',
  'MKE Ankaragücü',
  'Mladost Ljeskopolje',
  'MNK Izola',
  'Modena FC',
  'Modern Sport FC',
  'Moeskroen [nl]',
  'Molde FK',
  'Molinos El Pirata',
  'Molynes United',
  'Monagas Sport Club',
  'Monaghan',
  'Monarcas Morelia',
  'Mons [fr] | Bergen [nl]',
  'Mons Calpe SC',
  'Montedio Yamagata # All cities/towns in Yamagata',
  'Montego Bay United',
  'Montevideo City',
  'Montevideo Wanderers',
  'Montpellier HSC',
  'Montreal Impact',
  'Montrose',
  'Morecambe F.C.',
  'Morecambe FC',
  'Moreirense F.C.',
  'Moreirense FC',
  'Moroka Swallows',
  'Moss FK',
  'Mosta FC',
  'Motherwell F.C.',
  'Motherwell FC',
  'Motor Lublin',
  'Mount Pleasant Football Academy',
  'Mouscron [fr] | Moeskroen [nl]',
  'MOVE South Shields FC',
  'MS Dimona',
  'MS Kafr Qasim',
  'MSV Duisburg',
  'MTK Budapest',
  'MTV Eintracht Celle',
  'Muaither SC',
  'Municipal Grecia',
  'Municipal Pérez Zeledón',
  'Mushuc Runa SC',
  'MVV Maastricht',
  'Myllykosken Pallo -47',
  'Málaga CF',
  'Mérida',
  'Mérida AD',
  'Mörfelder Landstraße 362 // 60528 Frankfurt am Main',
  'MŠK Považská Bystrica',
  'MŠK Púchov',
  'MŠK Žilina',
  'N.E.C. (football club)',
  'NAC Breda',
  'Nacional de Montevideo',
  'Nacional Potosí',
  'Nagoya Grampus',
  'Name',
  'Nantong Zhiyun FC',
  'Nantwich Town FC',
  'Nashville SC',
  'National Bank SC',
  'Naval 1º de Maio',
  'Naxxar Lions FC',
  'ND Beltinci',
  'ND Gorica',
  'ND Mura 05 (2005-2013)',
  'ND Primorje',
  'Nea Salamis Famagusta FC',
  'Neath FC',
  'NEC Nijmegen',
  'Neckarsulmer Sport-Union',
  'Neftekhimik Nizhnekamsk',
  'Neftochimik Burgas',
  'Neftçi PFK',
  'Nelson FC',
  'Nest-Sotra Fotball',
  'Neuchâtel Xamax FCS',
  'New Brighton Tower FC (1898-1901)',
  'New England Revolution',
  'New Mexico United',
  'New York City',
  'New York City FC',
  'New York Cosmos',
  'New York Red Bulls',
  'New York Red Bulls U23',
  'Newcastle & Northumberland | Northumberland ## note: added Newcastle & - why? why not?',
  'Newcastle East End FC',
  'Newcastle United',
  'Newcastle United F.C.',
  'Newcastle United FC',
  'Newcastle United Jets',
  'Newcastle West End FC',
  "Newell's Old Boys",
  'Newington FC',
  'Newport County A.F.C.',
  'Newport County AFC',
  'Newry City AFC',
  'Newtown AFC',
  'Niedersachsen',
  'Niederösterreich',
  'Niki Volou FC',
  'NK Aluminij',
  'NK Bistrica',
  'NK Bravo',
  'NK Brotnjo',
  'NK Celje',
  'NK Croatia Sesvete (1957-2012)',
  'NK Domžale',
  'NK GOŠK Gabela',
  'NK Hrvatski Dragovoljac',
  'NK IB Ljubljana',
  'NK Inter Zaprešić',
  'NK Istra',
  'NK Izola (1923-1996)',
  'NK Kamen Ingrad (1929-2008)',
  'NK Karlovac',
  'NK Krško',
  'NK Lokomotiva Zagreb',
  'NK Lučko Zagreb',
  'NK Maribor',
  'NK Međimurje Čakovec',
  'NK Mura (1924-2005)',
  'NK Nafta',
  'NK Olimpija Ljubljana',
  'NK Osijek',
  'NK Posušje',
  'NK Primorje (1924-2011)',
  'NK Radomlje',
  'NK Rogaška',
  'NK Rudar Velenje',
  'NK Rudeš',
  'NK Slaven Belupo',
  'NK Tabor Sezana',
  'NK Trešnjevka Zagreb',
  'NK Triglav',
  'NK Varaždin',
  'NK Veres Rivne',
  'NK Zadar',
  'NK Zagreb',
  'NK Čelik Zenica',
  'NK Široki Brijeg',
  'NK Žepče (1919-2010)',
  'Nordic United FC',
  'Nordrhein-Westfalen',
  'Norfolk',
  'Norrby IF',
  'North Carolina FC',
  'North Ferriby United AFC',
  'North Yorkshire | Yorkshire',
  'Northampton Town F.C.',
  'Northampton Town FC',
  'Northamptonshire',
  'Northeast Utd',
  'Northumberland ## note: added Newcastle & - why? why not?',
  'Northwich Victoria FC',
  'Norwich City',
  'Norwich City F.C.',
  'Norwich City FC',
  'Notodden FK',
  'Nottingham Forest F.C.',
  'Nottingham Forest FC',
  'Nottinghamshire',
  'Notts County F.C.',
  'Notts County FC',
  'Novara',
  'NSÍ Runavík',
  'NTX Rayados',
  'Nueva Chicago',
  'Nuneaton Borough FC',
  'NY Red Bulls',
  'Nyköping BIS',
  'Nykøbing FC',
  'Nyíregyháza Spartacus',
  'Náutico PE',
  'Næstved BK',
  'Nîmes Olympique',
  'NŠ Mura',
  "O'Higgins FC",
  'Oberösterreich',
  'OC Safi',
  'Odds BK',
  'Odense BK',
  'Odense Boldklub',
  'Odra Opole',
  'Odra Wodzisław',
  'Oeste Futebol Clube',
  'Oeste SP',
  'OFC Sliven',
  'Offenburger FV',
  'OFI Crete FC',
  'OFK Beograd',
  'OFK Bečej',
  'OFK Grbalj',
  'OFK Petrovac',
  'OFK Titograd',
  'OGC Nice',
  'OH Leuven',
  'Oita Trinita',
  'Oita Trinita # All cities/towns in Oita',
  'OKC Energy FC',
  'OKS Stomil Olsztyn',
  'Oldham Athletic A.F.C.',
  'Oldham Athletic AFC',
  'Olimpik-Şüvälan PFK',
  'Olimpo Bahía Blanca',
  'Olympiacos Piraeus FC',
  'Olympiacos Volou 1937 FC',
  'Olympiakos Nicosia FC',
  'Olympique de Béja',
  'Olympique de Marseille',
  'Olympique Lyonnais',
  'Olympique Marseille',
  'Omiya Ardija',
  'Omonia Aradippou # Aradippou - a settlement on the outskirts of the city of Larnaca',
  'Once Caldas',
  'Onsala BK',
  'Ontinyent 1931 CF',
  'Ontinyent CF (1947-2019)',
  'Oost-Vlaanderen',
  'Oost-Vlaanderen › Vlaanderen | Oost-Vlaanderen',
  'Operário Ferroviário',
  'Operário Ferroviário Esporte Clube',
  'OPS Oulu',
  'Orange County FC',
  'Orange County SC',
  'Orduspor',
  'Orense',
  'Orlando City',
  'Orlando City SC',
  'Orlando Pirates',
  'Orsomarso SC',
  'Os Belenenses',
  'Oskarshamns AIK',
  'Osmanlıspor Ankara',
  'Othellos Athienou',
  'Oud-Heverlee Leuven',
  'Oxford City FC',
  'Oxford United F.C.',
  'Oxford United FC',
  'Oxfordshire',
  'Oțelul Galați',
  'Pachuca',
  'Pacific FC',
  'Paderborner Str. 89 // 33104 Paderborn',
  'PAE Chania',
  'Pafos FC',
  'Paganese Calcio',
  'Paide Linnameeskond',
  'Paksi SE',
  'Palermo FC',
  'Palloseura Kemi Kings',
  'Palmaflor del Trópico',
  'Palmeiras SP',
  'Panachaiki FC',
  'Panathinaikos FC',
  'Pandurii Târgu Jiu',
  'Panelefsiniakos FC',
  'Panetolikos GFS',
  'Panevėžys',
  'Paniliakos FC',
  'Panionios GSS',
  'Panserraikos FC',
  'Panthrakikos FC',
  'PAOK FC',
  'Paraná Clube',
  'Pari Nizhny Novgorod',
  'Paris FC',
  'Paris Saint-Germain',
  'Paris Saint-Germain F.C.',
  'Paris SG',
  'Parma Calcio',
  'Pars Jonoubi Jam',
  'Partick Thistle',
  'Partick Thistle F.C.',
  'PAS Giannina FC',
  'PAS Lamia',
  'Paseo del Centenario 9211 Local 3 Módulo 6',
  'Patriotas Boyacá',
  'Patro Eisden',
  'Patronato',
  'Pau FC',
  'Paysandu SC',
  'PEC Zwolle',
  'Pendikspor',
  'Penya Encarnada',
  'Penybont FC',
  'PEPO Lappeenranta',
  'Perpignan FC',
  'Persepolis FC',
  'Perth Glory',
  'Pescara',
  'Peterborough United F.C.',
  'Peterborough United FC',
  'Peterhead',
  'Petrojet',
  'Petrol Ofisi SK (1954-2010)',
  'Petrolero del Chaco',
  'Peykan',
  'Pezoporikos Larnaca (1927-1994)',
  'PFC Akademik Sofia',
  'PFC Beroe Stara Zagora',
  'PFC Botev Plovdiv',
  'PFC Cherno More Varna',
  'PFC CSKA Moscow',
  'PFC CSKA Moskva',
  'PFC CSKA Sofia',
  'PFC Krylia Sovetov Samara',
  'PFC Krylya Sovetov Samara',
  'PFC Levski Sofia',
  'PFC Litex Lovech',
  'PFC Lokomotiv Plovdiv',
  'PFC Lokomotiv Sofia',
  'PFC Lokomotiv Stara Zagora (1934-2009)',
  'PFC Ludogorets Razgrad',
  'PFC Marek Dupnitsa',
  'PFC Montana',
  'PFC Slavia Sofia',
  'PFC Sochi',
  'PFK Turan Tovuz',
  'Pharco FC',
  'Philadelphia Lone Star FC',
  'Philadelphia Union',
  'Phoenix Rising FC',
  'Piacenza Calcio',
  'Piast Gliwice',
  'Piteå IF',
  'Pittsburgh Riverhounds SC',
  'PK-35 Vantaa',
  'Platanias FC',
  'Platense',
  'Plymouth Argyle F.C.',
  'Plymouth Argyle FC',
  'Podbeskidzie Bielsko-Biała',
  'POFC Botev Vratsa',
  'Pogoń Szczecin',
  'Pohang Steelers',
  'Poli Timișoara',
  'Polideportivo Ejido',
  'Polissya Zhytomyr',
  'Polokwane City',
  'Polonia Bytom',
  'Ponte Preta',
  'Pontedera',
  'Pontevedra CF',
  'Pordenone Calcio',
  'Port Talbot Town FC',
  'Port Vale F.C.',
  'Port Vale FC',
  'Portadown FC',
  'Porthmadog FC',
  'Portimonense S.C.',
  'Portimonense SC',
  'Portland Timbers',
  'Portmore United',
  'Portogruaro Calcio ASD',
  'Portsmouth F.C.',
  'Portsmouth FC',
  'Portuguesa',
  'Portuguesa FC',
  'Post SV Wien',
  'Potenza Calcio',
  'Potros UAEM',
  'Prestatyn Town FC',
  'Preston North End F.C.',
  'Preston North End FC',
  'Preußen Münster',
  'Pro Patria',
  'Pro Vercelli',
  'Prol. Luis Vega y Monroy 409-4',
  'Proodeftiki FC',
  'Provincia Córdoba',
  'Provincia Entre Ríos',
  'Provincia Mendoza',
  'Provincia Misiones',
  'Provincia San Juan',
  'Provincia Santa Fe',
  'Provincia Tucumán',
  'Prötschhofstrasse 26 // 5082 Grödig',
  'PSV Eindhoven',
  'Puebla F.C.',
  'Puebla FC',
  'Puebla Fútbol Club',
  'Puerto Rico Islanders',
  'Pumas UNAM',
  'Puntarenas FC',
  'Puskás Akadémia FC',
  'Puszcza Niepołomice',
  'Pyramids FC',
  'Pápai FC (1995-2015)',
  'Pärnu JK Vaprus',
  'Pécsi MFC',
  'PΑC Omonia 29M',
  'Qarabağ FK',
  'Qingdao Huanghai FC',
  'Qingdao West Coast',
  'Queen of the South',
  "Queen's Park",
  'Queens Park Rangers',
  'Queens Park Rangers F.C.',
  'Queens Park Rangers FC',
  'Querétaro FC',
  'Querétaro Fútbol Club',
  'Quick Boys',
  'Quilmes AC',
  'Qviding FIF',
  'R. Charleroi S.C.',
  'R. Charleroi SC',
  'R. Mouscron-Péruwelz',
  'R.S.C. Anderlecht',
  'RAA Louviéroise',
  'Rabat Ajax',
  'Racing Besançon',
  'Racing Club',
  'Racing Club de Avellaneda',
  'Racing Club de France',
  'Racing CM',
  'Racing FC Union Lëtzebuerg',
  'Racing Ferrol',
  'Radomiak Radom',
  'RAEC Mons',
  'Raith Rovers',
  'Raja Casablanca',
  'Raków Częstochowa',
  'Rampla Juniors',
  'Randers FC',
  'Randers Freja',
  'Rangers F.C.',
  'Rangers FC',
  'Ranheim',
  'Rapid București',
  'Rapid JC Heerlen (1954-1962)',
  'Raufoss IL',
  'Ravenna FC',
  'Rayo Vallecano',
  'Rayo Zuliano',
  'RB Bragantino',
  'RB Brasil',
  'RB Leipzig',
  'RBC Roosendaal',
  'RC Celta de Vigo',
  'RC Celta Vigo',
  'RC Lens',
  'RC Strasbourg',
  'RC Strasbourg Alsace',
  'RCA Zemamra',
  'RCD Espanyol',
  'RCD La Coruña',
  'RCD Mallorca',
  'Reading F.C.',
  'Reading FC',
  'Reading United AC',
  'Real Betis',
  'Real Cartagena',
  'Real CD España',
  'Real Cundinamarca',
  'Real Estelí',
  'Real Jaén CF',
  'Real Madrid',
  'Real Madrid Castilla',
  'Real Madrid CF',
  'Real Monarchs',
  'Real Murcia CF',
  'Real Oviedo',
  'Real Potosí',
  'Real Racing Santander',
  'Real Salt Lake',
  'Real Santa Cruz',
  'Real Santander',
  'Real Sociedad',
  'Real Tomayapo',
  'Real Unión',
  'Real Valladolid',
  'Real Valladolid CF',
  'Real Zaragoza',
  'Recreativo Huelva',
  'Red Boys Differdange (1907-2003)',
  'Red Bull Bragantino',
  'Red Star Belgrade',
  'Red Star FC',
  'REFORM Ardwick FC',
  'REFORM Burslem Port Vale FC',
  'REFORM FC Pasching ⇒ FC Juniors OÖ ## use RENAME - why? why not?',
  'REFORM Newton Heath FC',
  'Reggina',
  "RENAME Barnsley St. Peter's FC",
  'RENAME Birmingham FC',
  'RENAME Chesterfield FC',
  'RENAME Chesterfield Town FC',
  'RENAME Clapton Orient FC',
  'RENAME Glossop North End FC',
  'RENAME Millwall Athletic FC',
  'RENAME Royal Arsenal FC',
  'RENAME Scunthorpe & Lindsey United FC',
  'RENAME The Arsenal FC',
  'RENAME The Wednesday FC',
  'RENAME USK Anif ⇒ FC Liefering',
  'RENAME Walsall Town Swifts FC',
  'RENAME Woolwich Arsenal FC',
  'RENAME WSG Wattens ⇒ WSG Tirol',
  'Reno 1868 FC',
  'Renofa Yamaguchi',
  'Resistencia FC',
  'Resovia Rzeszów',
  'RFC Liège',
  'RFC Seraing',
  'Rheinland-Pfalz',
  'Rheinlanddamm 207-209 // 44137 Dortmund',
  'Rhyl FC',
  'Richard-Herrmann-Platz 1 // 60386 Frankfurt am Main',
  'Richards Bay FC',
  'Richmond Kickers',
  'Rimini FC SSD',
  'Rio Ave F.C.',
  'Rio Ave FC',
  'Rio Grande Valley FC Toros',
  'Rionegro Águilas',
  'River Plate',
  'RKC Waalwijk',
  'RM Hamm Benfica',
  'RNK Split',
  'Roaring Lions FC',
  'Roasso Kumamoto',
  'Robert-Enke-Straße 1 // 30169 Hannover',
  'Rochdale A.F.C.',
  'Rochdale AFC',
  'Roda JC',
  'Roda JC Kerkrade',
  'Rodez AF',
  'Rosario Central',
  'Rosenborg BK',
  'Ross County F.C.',
  'Ross County FC',
  'Rostocker FC',
  'Rot Weiss Ahlen',
  'Rot-Weiss Essen',
  'Rot-Weiß Koblenz',
  'Rot-Weiß Oberhausen',
  'Rotherham County FC (1870-1925)',
  'Rotherham Town FC',
  'Rotherham Town FC (1899-1925)',
  'Rotherham United F.C.',
  'Rotherham United FC',
  'Rotor',
  'Rovaniemen Palloseura',
  'Royal AM',
  'Royal Antwerp F.C.',
  'Royal Antwerp FC',
  'Royal Excel Mouscron',
  'Royal Pari FC',
  'RS Berkane',
  'RSC Anderlecht',
  'RSV Meinerzhagen',
  'Ruch Chorzów',
  'Rushden & Diamonds (1992-2011)',
  'Rutland',
  'RW Rankweil',
  'RWD Molenbeek',
  'Rīga FC',
  'S.C. Braga',
  'S.L. Benfica',
  'S.P.A.L.',
  'S.S. Lazio',
  'S.S.C. Napoli',
  'S.V. Zulte Waregem',
  'Saarland',
  'Sabah FC',
  'Sabail',
  'Sachsen',
  'Sachsen-Anhalt',
  'Sacramento Republic FC',
  'Sagan Tosu',
  'Saint Johnstone FC',
  'Saint Louis City',
  'Saint Louis FC (2014-2020)',
  'Saint Mirren FC',
  'Saint-Gilloise',
  'SAK',
  'SAK Klagenfurt',
  'Sakaryaspor',
  'Salernitana',
  'Salford City FC',
  'Salgótarjáni BTC',
  'Salisbury City FC (1947-2014)',
  'Salisbury FC (2015-)',
  'Salon Palloilijat',
  'Salsa Ballers FC',
  'Salzburg',
  'Sambenedettese',
  'Sampaio Corrêa FC',
  'Samsunspor',
  'San Antonio Bulo Bulo',
  'San Antonio FC',
  'San Diego Loyal SC',
  'San Francisco FC',
  'San Jose Earthquakes',
  'San Juan | Provincia San Juan',
  'San Lorenzo',
  'San Lorenzo de Almagro',
  'San Luis FC (1957-2013)',
  'San Marino Academy',
  'San Martín de Tucumán',
  'San Martín San Juan',
  'San Pablo No. 100',
  'Sandecja Nowy Sącz',
  'Sandefjord',
  'Sandnes Ulf',
  'Sandvikens IF',
  'Sanfrecce Hiroshima',
  'Sangju Sangmu',
  'Sankt Pölten',
  'Santa Cruz',
  'Santa Fe | Provincia Santa Fe',
  'Santa Lucia',
  'Santa Lucía Cotzumalguapa',
  'Santamarina',
  'Santiago Wanderers',
  'Santo André',
  'Santos de Guápiles',
  'Santos de Nasca FC',
  'Santos FC',
  'Santos Laguna',
  'Santos SP',
  'Sarmenstorf FC',
  'Sarmiento Junín',
  'Sarpsborg 08',
  'Sarıyer SK',
  'SAS Épinal',
  'SBV Excelsior',
  'SBV Excelsior Rotterdam',
  'SBV Vitesse',
  'SC Admira Dornbirn',
  'SC Admira Gföhl',
  'SC Austria Lustenau',
  'SC Bad Sauerbrunn',
  'SC Balerna',
  'SC Bastia',
  'SC Beira-Mar',
  'SC Bettembourg',
  'SC Binningen',
  'SC Braga',
  'SC Brunn am Gebirge',
  'SC Brühl',
  'SC Buochs',
  'SC Cambuur',
  'SC Campomaiorense',
  'SC Cham',
  'SC Covilhã',
  'SC Dnipro-1',
  'SC Echsenbach',
  'SC Eendracht Aalst',
  'SC Eltersdorf',
  'SC Emmen',
  'SC Faetano',
  'SC Farense',
  'SC Fortuna Köln',
  'SC Freiburg',
  'SC Golling',
  'SC Guntersdorf',
  'SC Hauenstein',
  'SC Heerenveen',
  'SC Imst',
  'SC Kalsdorf',
  'SC Korneuburg',
  'SC Krems',
  'SC Kriens',
  'SC Kundl',
  'SC Leopoldsdorf',
  'SC Marchtrenk',
  'SC Neusiedl am See',
  'SC Olhanense',
  'SC Ostbahn XI',
  'SC Paderborn 07',
  'SC Pinkafeld',
  'SC Preußen Münster',
  'SC Red Star Penzing',
  'SC Retz',
  'SC Rheindorf Altach',
  'SC Ritzing',
  'SC Röthis',
  'SC Salgueiros',
  'SC Schwaz',
  'SC Schwyz',
  'SC Schöftland',
  'SC St. Martin',
  'SC Tasmania 1900 Berlin (-1973)',
  'SC Tavriya Simferopol',
  'SC Telstar',
  'SC Trausdorf',
  'SC União Torreense',
  'SC Verl',
  'SC Victoria Hamburg',
  'SC Weiche Flensburg 08',
  'SC Weißenkirchen',
  'SC Weiz',
  'SC Wiedenbrück',
  'SC Wiener Neustadt',
  'SC-ESV Parndorf',
  'Scarborough Athletic FC',
  'Scarborough FC (1879-2007)',
  'SCC Mohammédia',
  'Schalke 04',
  'Schleswig-Holstein',
  'Schnabelholz 1 // 6844 Altach',
  'Schwarzwaldstr. 193 // 79117 Freiburg',
  'SCR Altach',
  'SCU Ardagger # Bezirk Amstetten',
  'Scunthorpe United F.C.',
  'Scunthorpe United FC',
  'SD Amorebieta',
  'SD Aucas',
  'SD Compostela',
  'SD Eibar',
  'SD Huesca',
  'SD Logroñés',
  'SD Ponferradina',
  'Seattle Sounders FC',
  'Sektzia Nes Tziona FC',
  'Senglea Athletic FC',
  'Seongnam Ilhwa Chunma',
  'Sepsi Sfântu Gheorghe',
  'Servette FC',
  'Servette Genève',
  'Sevilla FC',
  'SF Baumberg',
  'SF Lotte',
  'SF Siegen',
  'SFC Etar Veliko Tarnovo',
  'SFC Opava',
  'SFC Slutsk',
  'SG Aumund-Vegesack',
  'SG Großaspach',
  'SG Sachsen Leipzig (2011-2014)',
  'SG Sonnenhof Großaspach',
  'SG Wattenscheid 09',
  'Shamrock Rovers FC',
  'Shandong Luneng Taishan',
  'Shandong Taishan',
  'Shanghai Greenland Shenhua',
  'Shanghai Port FC',
  'Shanghai Shenxin',
  'Shanghai SIPG F.C.',
  'Sheffield United F.C.',
  'Sheffield United FC',
  'Sheffield Wednesday F.C.',
  'Sheffield Wednesday FC',
  'Shelbourne FC',
  'Shenzhen FC',
  'Shijiazhuang Ever Bright',
  'Shimizu S-Pulse',
  'Shinnik',
  'Shonan Bellmare',
  'Shonan Bellmare # Southcentral cities/town in Kanagawa',
  'Shrewsbury Town F.C.',
  'Shrewsbury Town FC',
  'Shropshire',
  'Signal FC',
  'Siirtspor',
  'Silkeborg IF',
  'Simurq PFK (2005-2015)',
  'Sint-Truidense V.V.',
  'Sint-Truidense VV',
  'Sivasspor',
  'SJK Akatemia',
  'SJK Seinäjoki',
  'SK Bad Wimsbach',
  'SK Brann',
  'SK Dynamo České Budějovice',
  'SK Haugar',
  'SK Kladno',
  'SK Liepājas Metalurgs',
  'SK Líšeň',
  'SK Maria Saal',
  'SK Rapid Wien',
  'SK Sered',
  'SK Sigma Olomouc',
  'SK Slavia Prague',
  'SK Slavia Praha',
  'SK Sturm Graz',
  'SK Treibach',
  'SK Vorwärts Steyr',
  'SKA Khabarovsk',
  'Skeid Fotball',
  'Skive IK',
  'SKN St. Pölten',
  'Skonto FC (1991-2006)',
  'SKU Amstetten',
  'Skála ÍF',
  'Skövde AIK',
  'SL Benfica',
  'Slavia Praha',
  'Sliema Wanderers FC',
  'Sligo Rovers FC',
  'Sloga Jugomagnat Skopje (1927-2009)',
  'Slough Town FC',
  'SM Caen',
  'Small Heath FC',
  'Smouha',
  'Smouha SC',
  'SO Cholet',
  'Sociedade Esportiva do Gama',
  'Sociedade Esportiva Palmeiras',
  'Sogndal',
  'Sokol',
  'Solihull Moors FC',
  'Sollentuna FK',
  'Somerset',
  'Soroksár SC',
  'Sousa EC',
  'South Georgia Tormenta FC',
  'South Shields FC',
  'South Shore FC',
  'South Yorkshire | Yorkshire',
  'Southampton F.C.',
  'Southampton FC',
  'Southend United F.C.',
  'Southend United FC',
  'Southern United',
  'Southport FC',
  'SP Cailungo',
  'SP La Fiorita',
  'SP Tre Fiori',
  'SP Tre Penne',
  'SPAL 2013 Ferrara',
  'SPAL Ferrara',
  'Sparta Praha',
  'Sparta Rotterdam',
  'Spartak Moskva',
  'Spartak Nalchik',
  'Spartak Plovdiv',
  'Spezia Calcio',
  'SPG Friedburg/Pöndorf',
  'SPG Pregarten',
  'SPG Silz/Mötz',
  'Spora Luxemburg (1923-2005)',
  'Sport Boys',
  'Sport Boys Warnes',
  'Sport Club Corinthians Paulista',
  'Sport Club do Recife',
  'Sport Club Internacional',
  'Sport Huancayo',
  'Sport Recife',
  'Sportfreunde Dorfmerkingen',
  'Sportfreunde Lotte',
  'Sporting Charleroi',
  'Sporting CP',
  'Sporting Cristal',
  'Sporting de Espinho',
  'Sporting Fingal FC',
  'Sporting Gijón',
  'Sporting Kansas City',
  'Sporting San José',
  'Sporting San Miguelito',
  'Sporting Toulon Var',
  'Sportivo Ameliano',
  'Sportivo Luqueño',
  'Sportivo Trinidense',
  'Sportul Studențesc București',
  'Sportunion Mauer',
  'SpVgg Ansbach',
  'SpVgg Bayreuth',
  'SpVgg Greuther Fürth',
  'SpVgg Hankofen-Hailing',
  'SpVgg Unterhaching',
  'SR Delémont',
  'SR Donaufeld',
  'SS Arezzo',
  'SS Cosmos',
  'SS Fidelis Andria',
  'SS Folgore',
  'SS Juve Stabia',
  'SS Lazio',
  'SS Murata',
  'SS Pennarossa',
  'SS Robur Siena',
  'SSC Napoli',
  'SSD Latina Calcio',
  'SSV Jahn Regensburg',
  'SSV Jeddeloh',
  'SSV Reutlingen 05',
  'SSV Ulm',
  'St Johnstone F.C.',
  'St Johnstone FC',
  "St Joseph's FRAC",
  'St Mirren F.C.',
  "St Patrick's Athletic FC",
  'St. Albans City FC',
  'St. Patrick FC Żabbar',
  'St. Pölten | Sankt Pölten',
  'Stabæk',
  'Stade Brestois 29',
  'Stade Briochin',
  'Stade de Reims',
  'Stade Dudelange (1913-1991)',
  'Stade Lausanne-Ouchy',
  'Stade Lavallois',
  'Stade Malherbe Caen',
  'Stade Rennais F.C.',
  'Stade Rennais FC',
  'Stadionstraße 1b // 6020 Innsbruck',
  'Stadionstraße 2/3 // 5071 Wals-Siezenheim ## Salzburg',
  'Stadionweg 5/1 // 73430 Aalen',
  'Stafford Rangers FC',
  'Staffordshire',
  'Stal Mielec',
  'Stal Rzeszów',
  'Stalybridge Celtic FC',
  'Standard Liège',
  'Steaua București',
  'Steiermark',
  'Stellenbosch United',
  'Stenhousemuir',
  'Sternäckerweg 118 // 8042 Graz',
  'Stevenage F.C.',
  'Stevenage FC',
  'Stirling Albion',
  'Stjarnan',
  'Stockport County FC',
  'Stoke City F.C.',
  'Stoke City FC',
  'Stoke FC',
  'Stourbridge FC',
  'Stranraer',
  'Strømmen IF',
  'Strømsgodset IF',
  'Stuttgarter Kickers',
  'SU Bad Leonfelden',
  'Sud América',
  'Suffolk',
  'Sumqayıt FK',
  'Sunderland A.F.C.',
  'Sunderland AFC',
  'SuperSport United',
  'Surrey',
  'Sussex (East)',
  'Sussex (West)',
  'Sussex, East',
  'Sussex, West',
  'Sutton United FC',
  'Suwon Bluewings',
  'SV Alemannia Waldalgesheim',
  'SV Atlas Delmenhorst',
  'SV Babelsberg 03',
  'SV Bad Ischl',
  'SV Bad Schallerbach',
  'SV Darmstadt 98',
  'SV Dellach/Gail',
  'SV Donau Wien',
  'SV Drochtersen/Assel',
  'SV Eichede # from the Eichede suburb of Steinburg',
  'SV Elversberg',
  'SV Falkensee-Finkenkrug',
  'SV Frauental',
  'SV Fügen',
  'SV Gaflenz',
  'SV Gloggnitz',
  'SV Gmunden',
  'SV Grieskirchen',
  'SV Grödig',
  'SV Grün-Weiß Micheldorf',
  'SV Haitzendorf',
  'SV Hall',
  'SV Heiligenkreuz',
  'SV Heimstetten',
  'SV Horn',
  'SV Höngg',
  'SV Innsbruck',
  'SV Kuchl',
  'SV Lafnitz',
  'SV Leobendorf',
  'SV Linx',
  'SV Lippstadt 08',
  'SV Mattersburg',
  'SV Meppen',
  'SV Morlautern # Morlautern suburb of the city of Kaiserslautern',
  'SV Neuberg',
  'SV Oberachern',
  'SV Oberwart',
  'SV Rehberg',
  'SV Reutte',
  'SV Ried',
  'SV Robinhood',
  'SV Roßbach/Verscheid',
  'SV Rödinghausen',
  'SV Sandhausen',
  'SV Schaffhausen',
  'SV Schalding-Heining',
  'SV Schott Jena',
  'SV Schwechat',
  'SV Seekirchen',
  'SV Sieghartskirchen',
  'SV Spittal/Drau',
  'SV St. Jakob/Rosental',
  'SV St. Margarethen',
  'SV Stegersbach',
  'SV Straelen',
  'SV Straßwalchen',
  'SV Stripfing',
  'SV SVV',
  'SV Telfs',
  'SV Todesfelde',
  'SV Waldhof Mannheim',
  'SV Waldkirch',
  'SV Wallern',
  'SV Wals-Grünau',
  'SV Wehen Wiesbaden',
  'SV Werder Bremen',
  'SV Wienerberg',
  'SV Wildon',
  'SV Wilhelmshaven',
  'SV Wimpassing',
  'SV Wörgl',
  'SV Zulte Waregem',
  'SV Zwentendorf',
  'SVg Purgstall',
  'SVG Reichenau',
  'SW Bregenz',
  'Swansea City',
  'Swansea City A.F.C.',
  'Swansea City AFC',
  'Swindon Town F.C.',
  'Swindon Town FC',
  'Sydney FC',
  'Sylvesterallee 7 // 22525 Hamburg',
  'Syrianska FC',
  'Szeged-Csanád Grosics Akadémia',
  'Szolnoki MÁV FC',
  'Szombathelyi Haladás',
  'Szombierki Bytom',
  'São Bento',
  'São José',
  'São Paulo FC',
  'Säbener Straße 51-57 // 81547 München',
  'Sønderjysk Elitesport',
  'SønderjyskE',
  'SønderjyskE Fodbold',
  'Săgeata Năvodari',
  'Tacoma Defiance',
  'Tacuary',
  "Tala'ea El Gaish",
  'Talleres de Córdoba',
  'Tampa Bay Mutiny',
  'Tampa Bay Mutiny (1996-2001)',
  'Tampa Bay Rowdies',
  'Tampere United',
  'Tampereen Pallo-Veikot',
  'Tampico Madero',
  'Tampines Rovers FC',
  'Tamworth FC',
  'Tanjong Pagar Utd',
  'Tanta SC',
  'Tarxien Rainbows FC',
  'Tasman United',
  'Tauro FC',
  'TB Tvøroyri',
  'Team Wellington',
  'Tegevajaro Miyazaki',
  'Telephonat Bani Sweif',
  'Telford United FC (1872-2004)',
  'Temperley',
  'Tempête FC',
  'Tennis Borussia Berlin',
  'Tepatitlán FC',
  'Terek Grozny',
  'Ternana',
  'Terrassa FC',
  'Thames AFC (1928-1932)',
  'The New Saints FC',
  'The Strongest',
  'The Villages SC',
  'Thespa Gunma',
  'Thisted FC',
  'Thrasyvoulos FC',
  'Throttur Reykjavik',
  'Thór Akureyri',
  'Thüringen',
  'Tianjin Quanjian',
  'Tianjin Teda F.C.',
  'Tianjin Tianhai (2006-2020)',
  'Tianjin Tigers',
  'Tiburones Rojos de Veracruz',
  'Tiburones Rojos Veracruz',
  'Tigres FC',
  'Tigres UANL',
  'Tiro Federal',
  'Tirol',
  'Tivoli Gardens',
  'TJ Sokol Dolná Zdana',
  'TJ Spartak Myjava',
  'Tlaxcala FC',
  'Tochigi SC',
  'Tokushima Vortis # All cities/towns in Tokushima',
  'Tokyo Verdy',
  'Tolosa CF',
  'Tom Tomsk',
  'Tombense FC',
  'Torino F.C.',
  'Torino FC',
  'Toronto FC',
  'Torpedo Metallurg Moskva',
  'Torpedo Moscow',
  'Torpedo Moskva',
  'Torquay United FC',
  'Torslanda IK',
  'Tosno',
  'Tottenham Hotspur',
  'Tottenham Hotspur F.C.',
  'Tottenham Hotspur FC',
  'Toulouse FC',
  'Tours FC',
  'TPS Turku',
  'Trabzonspor',
  'Tranmere Rovers F.C.',
  'Tranmere Rovers FC',
  'Trapani Calcio',
  'Treasure Beach',
  'Treaty United',
  'Trelleborgs FF',
  'Trikala FC',
  'Tromsdalen UIL',
  'Tromsø IL',
  'Troyes AC',
  'Trujillanos FC',
  'TS Galaxy FC',
  'Tsarsko Selo',
  'Tsarsko Selo Sofia',
  'TSG 1899 Hoffenheim',
  'TSG Balingen',
  'TSG Neustrelitz',
  'TSG Pfeddersheim # Pfeddersheim suburb of Worms',
  'TSV 1860 Munich',
  'TSV 1860 München',
  'TSV 1860 Rosenheim',
  'TSV 1896 Rain',
  'TSV Aubstadt',
  'TSV Buchbach',
  'TSV Hartberg',
  'TSV Havelse',
  'TSV München',
  'TSV Neumarkt',
  'TSV Schott Mainz',
  'TSV Schwaben Augsburg',
  'TSV St. Johann',
  'TSV Steinbach Haiger # based in Steinbach',
  'Tucanes FC',
  'Tucumán | Provincia Tucumán',
  'Tupi MG',
  'Turanspor',
  'TuS Bad Gleichenberg',
  'TuS Bersenbrück',
  'TuS Dassendorf',
  'TuS Erndtebrück',
  'TuS Koblenz',
  'TuS Makkabi Berlin',
  'Tuzlaspor',
  'Tvååkers IF',
  'TWL Elektra',
  'Tyne and Wear',
  'Tzeirei Kafr Kanna',
  'Täby FK',
  'Türkgücü München',
  'U Cluj',
  'U. de C.',
  'U.C. Sampdoria',
  'U.S. Sassuolo Calcio',
  'UC Sampdoria',
  'UCAM Murcia',
  'UD Almería',
  'UD Ibiza',
  'UD Las Palmas',
  'UD Logroñés',
  'UD Melilla',
  'UD Oliveirense',
  'UD Salamanca',
  'UD Socuéllamos',
  'UD Vecindario',
  'UD Vilafranquense (-2023)',
  'Udinese Calcio',
  'UE Engordany',
  'UE Llagostera',
  'UE Lleida (1939-2011)',
  'UE Sant Andreu',
  'UE Sant Julià',
  'UE Santa Coloma',
  'Ulisses FC',
  'Ullensaker/Kisa IL',
  'Ulsan HD FC',
  'Ulsan Hyundai',
  'UM Escobedo',
  'Umeå FC',
  'UMF Afturelding',
  'UMF Njarðvík',
  'UN Käerjéng 97',
  'Union Dietach',
  'Union Edelweiß Linz',
  'Union Fürstenwalde',
  'Union Gurten',
  'Union Innsbruck',
  'Union Luxembourg (1925-2005)',
  'Union Mondsee',
  'Union Mutilvera',
  'Union Ostermiething',
  'Union Perg',
  'Union Rohrbach/Berg',
  'Union St. Florian',
  'Union St. Martin/M.',
  'Union Vöcklamarkt',
  'Union Weißkirchen',
  'Unione Calcio Albinoleffe',
  'Unirea Slobozia',
  'Unirea Urziceni (1954-2017)',
  'Universidad Católica',
  'Universidad César Vallejo',
  'Universidad de Chile',
  'Universidad de Costa Rica',
  'Universidad Las Palmas',
  'Universidad Técnica de Cajamarca',
  'Universitario de Sucre',
  'Universitario de Vinto',
  'Universitatea Craiova',
  'University College Dublin AFC',
  'União da Madeira',
  'União de Leiria',
  'União São João',
  'Unión Comercio',
  'Unión de Santa Fe',
  'Unión Española',
  'Unión La Calera',
  'Unión Magdalena',
  'Unión Santa Fe',
  'Up Rising FC',
  'Ural Yekaterinburg',
  'Uralan',
  'Urawa Red Diamonds',
  'Urbs Reggina',
  'US Anconitana ASD',
  'US Arbedo',
  'US Avranches',
  'US Ben Guerdane',
  'US Boulogne',
  'US Catanzaro',
  'US Concarneau',
  'US Cremonese',
  'US Créteil',
  'US Hostert',
  'US Lecce',
  'US Monastir',
  'US Mondorf-les-Bains',
  'US Orléans',
  'US Palermo',
  'US Pistoiese',
  'US Quevilly-Rouen Métropole',
  'US Rumelange',
  'US Sassuolo Calcio',
  'US Touarga',
  'US Triestina Calcio',
  'USC Altenwörth',
  'USC Eugendorf',
  'USC Grafenwörth',
  'USC Kirchberg/W.',
  'USC Paloma Hamburg',
  'USC Schweiggers',
  'USK Anif',
  'USL Dunkerque',
  'USV Allerheiligen',
  'USV Groß Gerungs',
  'USV Hercules',
  'USV Langenlois',
  'USV Mettersdorf',
  'USV Raabs/Thaya',
  'USV Rudersdorf',
  'USV Scheiblingkirchen-Warth',
  'USV St. Anna',
  'UTA Arad',
  'Utsiktens BK',
  'V-Varen Nagasaki',
  'Vaasan Palloseura',
  'Valencia CF',
  'Valencia FC',
  'Valenciennes FC',
  'Valletta FC',
  'Valmiera FC',
  'Valour FC',
  'Valur Reykjavík',
  'Valznerweiherstraße 200 // 90480 Nürnberg',
  'Vancouver Whitecaps',
  'Vancouver Whitecaps FC',
  'Vanløse IF',
  'Vannes OC',
  'Vanspor FK',
  'Varbergs BoIS',
  'Varde IF',
  'Varese Calcio',
  'Varzim SC',
  'Vasa IFK',
  'Vasalunds IF',
  'Vasas FC',
  'Vasas SC',
  'VB Vágur (1905-2005)',
  'Vegalta Sendai',
  'Vejle',
  'Velež Mostar',
  'Venados FC',
  'Vendsyssel FF',
  'Venezia FC',
  'Ventforet Kofu',
  'Ventforet Kofu # All cities/towns in Yamanashi',
  'Veracruz',
  'Vere United',
  'Veria FC',
  'Vevey-Sports',
  'VfB Borussia Neunkirchen',
  'VfB Eichstätt',
  'VfB Germania Halberstadt',
  'VfB Hohenems',
  'VfB Leipzig (-2004)',
  'VfB Lübeck',
  'VfB Mödling (1911-1977)',
  'VfB Oldenburg',
  'VfB Stuttgart',
  'VfL Bochum',
  'VfL Oldenburg',
  'VfL Osnabrück',
  'VfL Wolfsburg',
  'VfR Aalen',
  'VfR Garching',
  'VfR Kleinhüningen',
  'VfR Mannheim',
  'VfR Neumünster',
  'VfV 06',
  'VfV 06 Hildesheim',
  'VfV Borussia 06',
  'VfV Borussia 06 Hildesheim',
  'VfV Hildesheim',
  'Vibonese Calcio',
  'Viborg FF',
  'Viby IF',
  'Victoria București (1949-1990)',
  'Videoton FC',
  'Vienna [en]',
  'Viking FK',
  'Viktoria Aschaffenburg',
  'Viktoria Plzeň',
  'Vila Nova Futebol Clube',
  'Vila Nova GO',
  'Villa Dálmine',
  'Villacher SV',
  'Villarreal CF',
  'Virginia United FC',
  'Virtus Entella',
  'Virtus FC',
  'Virtus Lanciano',
  'Vis Pesaro',
  'Vissel Kobe',
  'Vitesse Arnhem',
  'Vitosha Bistritsa',
  'Vitória de Guimarães',
  'Vitória de Setúbal',
  'Vitória F.C. ## Vitória de Setúbal',
  'Vitória S.C. ## Vitória de Guimarães',
  'Vladikavkaz',
  'VMFD Žalgiris',
  'Volga Nizhnii Novgorod',
  'Volgar-Astrakhan',
  'Volksfestplatz 2 // 4910 Ried i. Innkreis',
  'Volos FC',
  'Vorarlberg',
  'Voska Sport',
  'VSE St. Pölten (1920-1998)',
  'VSG Altglienicke',
  'VST Völkermarkt',
  'Vushtrria',
  'VV IJsselmeervogels # from Bunschoten - Spakenburg',
  'VVV Venlo',
  'VVV-Venlo',
  'Vác FC',
  'Västerås SK',
  'Vålerenga Fotball',
  'Vélez Sarsfield',
  'Víkingur Gøta',
  'Víkingur Reykjavík',
  'W Connection',
  'Waasland-Beveren',
  'Wacker Burghausen',
  'Wacker Nordhausen',
  'Wadi Degla',
  'WaiBOP United (-2016)',
  'Waitakere United',
  'Walsall F.C.',
  'Walsall FC',
  'Warrenpoint Town FC',
  'Warta Poznań',
  'Warwickshire',
  'Wasquehal Foot',
  'Waterford FC',
  'Waterhouse',
  'Waterschei Thor (1919-1988)',
  'Watford F.C.',
  'Watford FC',
  'Wealdstone FC',
  'Welling United FC',
  'Wellington Phoenix',
  'Welshpool Town FC',
  'Werder Bremen',
  'West Bromwich Albion',
  'West Bromwich Albion F.C.',
  'West Bromwich Albion FC',
  'West Chester Predators',
  'West Ham United',
  'West Ham United F.C.',
  'West Ham United FC',
  'West Midlands ## note: added Birmingham - why? why not?',
  'West Sussex | Sussex',
  'West Yorkshire | Yorkshire',
  'West-Vlaanderen',
  'West-Vlaanderen › Vlaanderen | West-Vlaanderen',
  'Western Sydney Wanderers',
  'Western United',
  'Weston-super-Mare AFC',
  'Wexford FC',
  'Weymouth FC',
  'Widzew Łódź',
  'Wien | Vienna [en]',
  'Wiener Neustadt',
  'Wiener Sport-Club',
  'Wiener Viktoria',
  'Wigan Athletic F.C.',
  'Wigan Athletic FC',
  'Wigan Borough FC (1920-1931)',
  'Willem II',
  'Willem II (football club)',
  'Willem II Tilburg',
  'Wiltshire',
  'Wimbledon FC',
  'Wisła Kraków',
  'Wisła Płock',
  'WKS Śląsk Wrocław',
  'Woking FC',
  'Wolfsberger AC',
  'Wolverhampton Wanderers F.C.',
  'Wolverhampton Wanderers FC',
  'Worcestershire',
  'Workington AFC',
  'Wormatia Worms',
  'Wr. Neustadt | Wiener Neustadt',
  'Wrexham AFC',
  'WSC Hertha Wels',
  'WSG Tirol',
  'WSG Wattens',
  'Wuhan Three Towns',
  'Wuhan Zall (2009-2023)',
  'Wuhan Zall F.C.',
  'Wuppertaler SV',
  'Wycombe Wanderers F.C.',
  'Wycombe Wanderers FC',
  'Wydad Casablanca',
  'Würzburger Kickers',
  'Xamax Neuchâtel',
  'Xanthi FC',
  'Xerez CD',
  'Xäzär Länkäran FK',
  'Yanbian Funde',
  'Yaracuyanos FC',
  'Yeni Malatyaspor',
  'Yenisey',
  'Yeovil Town F.C.',
  'Yeovil Town FC',
  'YF Juventus Zürich',
  'Yokohama F. Marinos',
  'Yokohama FC',
  'York City FC',
  'York9 FC',
  'Yorkshire (East)',
  'Yorkshire (North)',
  'Yorkshire (South)',
  'Yorkshire (West)',
  'Yorkshire, East',
  'Yorkshire, North',
  'Yorkshire, South',
  'Yorkshire, West',
  'YoungHeart Manawatu',
  'Yozgatspor',
  'Ypiranga FC',
  'Yverdon-Sport FC',
  'Zacatepec',
  'Zagłębie Lubin',
  'Zagłębie Sosnowiec',
  'Zagłębie Wałbrzych',
  'Zalaegerszegi TE',
  'Zamalek',
  'Zamora CF',
  'Zamora FC',
  'Zawisza Bydgoszcz',
  'ZED FC',
  'Zenit St. Petersburg',
  'Zeytinburnuspor',
  'Zhejiang FC',
  'Zhejiang Yiteng FC',
  'Zirä FK',
  'Zug 94',
  'Zulia FC',
  'Zvartnots-AAL FC (1997-2003)',
  'Zvijezda 09',
  'Zweigen Kanazawa',
  'Zürich City',
  'Ängelholms FF',
  'Åsane Fotball',
  'Åtvidabergs FF',
  'Çanakkale Dardanelspor',
  'Çaykur Rizespor',
  'Çorum',
  'Écija Balompié',
  'Évian TG',
  'Évian TG FC',
  'ÍA Akranes',
  'ÍBV Vestmannaeyjar',
  'ÍF Fuglafjørdur',
  'ÍF Vestri',
  'ÍR Reykjavík',
  'Örebro SK',
  'Örebro Syrianska IF',
  'Örgryte Göteborg',
  'Östers IF',
  'Östersunds FK',
  'Újpest FC',
  'Ümraniyespor',
  'ŁKS Łódź',
  'Şanlıurfaspor',
  'ŠK Slovan Bratislava',
  'Żurrieq FC',
  '⇒ Blackpool FC',
  '⇒ Burton United FC',
  '⇒ Newcastle United FC',
  '⇒ Rotherham United FC',
];
